In [1]:
## 파이썬 단점 속도가 느리다  => 계산속도가 느리다 =
## gpu , parallen computing (여러대 연결)

# 넘파이 씨로 만들어짐, 엔드어레이 벡터라이제이션이(여러개 데이터 하나로 묶은거포문없이 연산)라는걸로 만들어져서 빠르다

# 파이썬 인터프리터 언어인데 컴파일 할수 있게 해줌(cython(자료 타입 지정) c속도 근접하게 나옴, shed, skin, num)
# 컴파잃 할수 있어 속도 빠르다 pypy 파이썬으로 만든 (다이나믹타입, 스택,~~ 이런거 최적화 해서 5배빠름 문법 수정 할 필요 x pypy 설치(호환성문제))
# 글루 랭기지 - 다른 언어와 잘 붙는다. 병목현상 일어나는 부분을 c코드로 짜버린다. 
# 알고리즘

# => 이런방법으로 속도를 빠르게 만들수 있어

# 계산 관련해서 속도를 빠르게한 라이브러리가 넘파이(5~20배정도 빠르다)
# 빅데이터처리 => 속도 중요

In [2]:
# 넘파이쓰는이유 
# 속도 빠르다.  편하고 쉽다. 복잡한 계산을 빠르고 편하게 해주는 라이브러리
# 아나콘다 전세계 통일 컨티너리, 넘파이 만든 회사 넘파이 판다스 사이킷, 텐서플로우 파이토치 넘파이로만듬
# 밑바닥부터시작하는 딥러닝(넘파이로 밑부터 하나하나 알고리즘구현해가며 만들어감)
# 데이터구조, 알고리즘 => vectorization (컴파일러때) 행렬 한번에 여러개의 수를 계산 가능 simp(cpu 자체 벡터에 최적화된 연산 지원) 연산속도 줄어듬
# 넘파이는 cpu 지원 안함. 텐서플로 파이토치( cpu 지원하도록 다시만듬)
# 벡터 여러개의 데이터를 한묶음으로 만드는 애
# 중요! for문을 돌리지 않음 루프를 쓰면 속도가 느리다. (컴프리헨션, 이터레이터, 제너레이터, 재귀함수, 맵, 필터, 리듀스(하이 오더 펑션))
# 함수형 페러다임 for문 안쓴다 = 벡터라이제이션(포문안쓰고 벡터를 쓰는거, 어레이프로그램)
# 함수형 페러다임, 객체지향, 어레이프로그램(젤 어려움)
# 항상 빠른게 x 작은 n에서는 속도가 느릴수도 n이 상당이 커야 속도 빠름 (어레이프로그램)


In [3]:
# 1차원 벡터는 방향이 없다고 생각하자
# 2차원은은 매트릭스 
# 3차원 패널데이터 이런걸 텐서라고 한다. 텐서플로우는 이런 구조를 사용
# 애를 일반화하면 end array

n차 텐서플로우
사진 2차원
동영상 3차원(시간까지) + 갯수 4차원
어떤 현상을 벡터화시키는것이 핵심


In [4]:
# rgb 합쳐서 하나의 어레이

In [5]:
# 우리가 배울 모든 애들은 다 넘파이로 만들어져있다.
#

In [6]:
import numpy as np

In [7]:
dir(np) ## 대문자가 먼저나오는 이유 __dir 아스키 대문자 65 소문자 97 정렬문제 차이
        ## 파이썬은 상수 x 대문자로 이루어져 있으면 상수처럼 쓴다
        ## 파이썬 객체 인스턴스, 리터럴?
        ## 인스턴스화 하지 않고 다른 (자식,하위계층함수의 클래스 이용해서 인스턴스화하는거 =>팩토리 메소드(넘파이많음 np.array)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

In [8]:
__dir(np)

NameError: name '__dir' is not defined

In [21]:
a = np.array ## c로 데이터를 저장하는 방식, 포트란으로 데이터를 저장하는 방식 둘다 지원 해줌
            ## array 는 호모지니어스한 타입, 데이터 1개이상 리스트, 튜플
a = np.array((3,4)) ##(3,4 ) 0차원 스칼라 [3,4] 1차원 벡터


In [25]:
a ## 튜플로 했는데 리스트로 바뀌었다 mutable (swallow copy decopy) => mutable에서 나오는 문제점
    ## 아웃풋에 array 이렇게 나오는건 numpy 데이터 형태 array
    

array([3, 4])

In [26]:
type(a)  # n차원 dimension array nd

numpy.ndarray

In [60]:
a = np.array([[1,2],[3,4]]) #2ckdnjs

In [61]:
a

array([[1, 2],
       [3, 4]])

In [62]:
a.ndim # 차원 알려줌

2

In [65]:
a.shape ## 2행 2열  , 행렬 연산할때 모양 맞춰야 해서 중요하다!

(2, 2)

In [66]:
len(a)

2

In [67]:
a.flags  ## C _CONTIGUOUS F_ CONTI C방식이냐 포트란 방식이냐
            ## C는 데이터 저장할떄 옆으로 나란히 1,2,3,4, 이렇게 가로로 저장하는데 포트란은 1,3,2,4 이렇게 저장되어 있다. 세로로 저장

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [68]:
a.size  # 원소의 갯수

4

In [69]:
a.itemsize # 각 하나의 애가 몇비트인가

4

In [70]:
a.dtype ## 데이터 타입

dtype('int32')

In [73]:
b = np.array([[1,2],[3,4]]) 

In [78]:
x = [1,2,3,4]
y= [2,3,4,5]
# zz = []
# for x, y in x,y:
#     zz.append(x+y)
    
[a+b for a,b in zip(x,y)] ## + 이거 하나로 된다

[3, 5, 7, 9]

In [75]:
a+b  ## 원소끼리 계산해준다. => element wise 방식 

array([[2, 4],
       [6, 8]])

In [79]:
a

array([[1, 2],
       [3, 4]])

In [80]:
a.T   ## 선형대수때 배운 치환

array([[1, 3],
       [2, 4]])

In [32]:
# 판때기 하나하나마다 공백있다고 이해 데이터 하나 겹쳐져 있구나
a = np.array([[[1,2],[3,4]],[[1,2],[3,4]]]) #3차원

In [33]:
a

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [34]:
n = np.ndarray(0)

In [35]:
n


array([], dtype=float64)

In [36]:
type(n)

numpy.ndarray

In [37]:
a = np.array(['1',2,3]) # 나머지를 호모지니어스 하게 다 바꿔준다 문자열로  팩토리얼 메소드는 이렇게 호모지니어스로 다 바꿔준다

In [58]:
vars(a) ##__dict가 정의가 안되면 안나옴 인스턴스 변수 알수있는거

TypeError: vars() argument must have __dict__ attribute

In [ ]:
## dype c 데이터 타입지원해준다.
## 호모지니어스 이ㅣ기떄문에 빠르다, + c로만들어져있음

In [38]:
a   ## 리틀 엔디언 <, 빅 엔디언방식 > 

array(['1', '2', '3'], dtype='<U1')

In [54]:
n = np.array([0,"1"])  # 클래스 인스턴스, 리터럴, 팩토리

In [55]:
n

array(['0', '1'], dtype='<U11')

In [43]:
np.ndarray

array(['0', '1'], dtype='<U11')

In [85]:
n = np.ndarray([0, 3])

In [86]:
n

array([], shape=(0, 3), dtype=float64)

In [87]:
dir(np.ndarray())

TypeError: Required argument 'shape' (pos 1) not found

In [12]:
import array  ## 호모지니어스한 데이터 타입(스트링 3총사, range) : 다음 데이터타입이 뭔지 계싼할 필요 x => 계산 속도가 빠르다.
              ## 파이썬 공식 어레이는 속도 느리다 np,array 가 속도가 빠르다 호모지니어스한 타입 따라서 넘파이 어레이 쓴다

In [13]:
dir(array)

['ArrayType',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_array_reconstructor',
 'array',
 'typecodes']

In [53]:
a =array(1)

TypeError: 'module' object is not callable

In [56]:
# 리틀에디언 빅에디언
# <UI 넘파이는 C에서 하듯 int 8 16 이런거 하게해줌

In [57]:
n = np.ndarray([0,"1"])

TypeError: 'str' object cannot be interpreted as an integer

In [ ]:
varse