In [1]:
# numpy => c로되있따. 효율적인 자료구조(벡터라이제이션)
# 서브클래스 ㅏㅈ기만의 자료구조 배열로된거 많다(영상,이미지)
# 읽기위해서 헤더부분을 변경해야될부분이 많다. 

# http://www.labri.fr/perso/nrougier/from-python-to-numpy/ 여기 이거 보고 공부
## https://github.com/rougier/numpy-100   여기 문제 예제 다 쳐보기 공부

# 왜 벡터라이제이션 중요하고 왜 빠른지 다 있는 내용 이거 복습
# 답있는거 답없는거, 100 100 100 문제 해보기, 벡터라이제이션  이거도 과제

# + lms 과제도 있다

# 프로제트 피드백 안해준다

## reshape
## 자동적으로 모양을 맞춰줌 broadcast 복잡한 구조는 자동적으로 못맞춰준다.
## np.info

In [2]:
import numpy as np

In [8]:
np.lookfor('* array') ## create 에 관련된 메소드 다찾아줌

Search results for '* array'
----------------------------
numpy.exp
    Calculate the exponential of all elements in the input array.
numpy.cbrt
    Return the cube-root of an array, element-wise.
numpy.exp2
    Calculate `2**p` for all `p` in the input array.
numpy.fmax
    Element-wise maximum of array elements.
numpy.fmin
    Element-wise minimum of array elements.
numpy.modf
    Return the fractional and integral parts of an array, element-wise.
numpy.rint
    Round elements of the array to the nearest integer.
numpy.sqrt
    Return the positive square-root of an array, element-wise.
numpy.expm1
    Calculate ``exp(x) - 1`` for all elements in the array.
numpy.isnan
    Test element-wise for NaN and return result as a boolean array.
numpy.isnat
    Test element-wise for NaT (not a time) and return result as a boolean array.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, element

In [5]:
np.lookfor('reshape') ## create 에 관련된 메소드 다찾아줌

Search results for 'reshape'
----------------------------
numpy.ma.reshape
    Returns an array containing the same data with a new shape.
numpy.chararray.reshape
    Returns an array containing the same data with a new shape.
numpy.matrix.squeeze
    Return a possibly reshaped matrix.
numpy.reshape
    Gives a new shape to an array without changing its data.
numpy.add
    Add arguments element-wise.
numpy.dot
    Dot product of two arrays. Specifically,
numpy.ix_
    Construct an open mesh from multiple sequences.
numpy.pad
    Pads an array.
numpy.ptp
    Range of values (maximum - minimum) along an axis.
numpy.amax
    Return the maximum of an array or maximum along an axis.
numpy.amin
    Return the minimum of an array or minimum along an axis.
numpy.diag
    Extract a diagonal or construct a diagonal array.
numpy.flip
    Reverse the order of elements in an array along the given axis.
numpy.fmod
    Return the element-wise remainder of division.
numpy.isin
    Calculates `element 

In [6]:
np.info('reshape') ## info lookfor 하면 다 찾을수 있따 ## shit+o 하면 다보임

     *** Found in numpy ***
 reshape(a, newshape, order='C')

Gives a new shape to an array without changing its data.

Parameters
----------
a : array_like
    Array to be reshaped.
newshape : int or tuple of ints
    The new shape should be compatible with the original shape. If
    an integer, then the result will be a 1-D array of that length.
    One shape dimension can be -1. In this case, the value is
    inferred from the length of the array and remaining dimensions.
order : {'C', 'F', 'A'}, optional
    Read the elements of `a` using this index order, and place the
    elements into the reshaped array using this index order.  'C'
    means to read / write the elements using C-like index order,
    with the last axis index changing fastest, back to the first
    axis index changing slowest. 'F' means to read / write the
    elements using Fortran-like index order, with the first index
    changing fastest, and the last index changing slowest. Note that
    the 'C' and 'F' optio

In [9]:
a = np.array(100)

In [10]:
a  ## 0차 스칼라 묶는 구조체가 되야 1차

array(100)

In [ ]:
a = np.array([100])  ## 이게 1차

In [11]:
a = np.array([[100]])  ## 이게 2차

In [12]:
a

array([[100]])

In [16]:
a = np.array([[1,2,3],[4,5,6]]) ## 컴파 점으로 바꾸면 왜? 리스트?

In [17]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
## 여러개의 값을 하나의 값으로 줄이는방법 리덕션이 쉽게된다. stride 개념이 숨어있어서 빠른 연산 가능
## stride 보폭 등간격

In [138]:
a = np.arange(27) ## 1차? re!!

In [139]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [22]:
#reshape stride를 이용해서 변화시키는데 비용이 안든다 거의 바로됨 실시간 reshape 

In [24]:
a.shape ## 튜플로 표현 

(27,)

In [26]:
a.reshape(3,9)  ## reshape 27 이 갯수를 맞춰줘야 한다  ## 애는 임뮤터블 펑션이다/.
                ## 넘파이는 배열 일자 메모리 스트라이드는 그냥값보여주기용 편하게 따라서 리쉐이프로 바뀔필요가 없다. => 재할당 식으로해야함

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [27]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [28]:
b = a.reshape(3,9)  ## reshape 인거 할당했는데 a도 바뀐다 스왈로우 카피처럼 된다. 따라서 딥카피로 해야한다 카피한다 이런거 딥카피 한다는 뜻

In [29]:
b[0][0] = 100

In [30]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26])

In [31]:
## 따라서 이렇게 해야한다 실수 존나나옴 원본하고 같이 바뀜

In [32]:
b = a.reshape(3,9).copy()

In [33]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [34]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26])

In [40]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [36]:
b = a.reshape(3,-1)  # -1 은 오토매틱이란 뜻
                    # -1은 9로 바뀐다.

In [38]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [41]:
b = a.reshape(-1,-3)  # -1 은 오토매틱이란 뜻
                    # -1은 9로 바뀐다. -100이건 상관 x 관례상 -1 씀
                    # -1 가 붙으면 자동적으로 바꿔준다. re!! 뭐가 바뀌냐?? -  27이면 3 -1 하면 -1이 9로 알아서 된다

ValueError: can only specify one unknown dimension

In [142]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [145]:
a.resize(3,-1)

ValueError: negative dimensions not allowed

In [144]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [141]:
a.resize((-1,5))  ## resize 은 뮤터블 펑션이여서 자기자신이 바뀌어버린다. <=> reshape()
                  ## 상황에 따라서 맞는거 써야야한다.
                    ## 3,5 27 숫자 안맞춰도 알아서 잘라주거나 크게 만들면 0으로 채워준다.
                    ## -1 T쓰면 안된다
                    ## 뮤터블 쉽지만 실수할 경우가 많아서 가능한 임뮤터블 쓴다
                
                    ## 나왜 이거 안되냐?? re!!
                    

ValueError: negative dimensions not allowed

In [49]:
a

array([[100],
       [  1],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9],
       [ 10],
       [ 11],
       [ 12],
       [ 13],
       [ 14],
       [ 15],
       [ 16],
       [ 17],
       [ 18],
       [ 19],
       [ 20],
       [ 21],
       [ 22],
       [ 23],
       [ 24],
       [ 25],
       [ 26]])

In [53]:
## 스플릿은 모양을 쪼개주는데
## vertical 이랑 horizontal split

In [55]:
a.arange(27)

AttributeError: 'numpy.ndarray' object has no attribute 'arange'

In [56]:
a = a.reshape(3,9)

In [57]:
a

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [58]:
## 넘파이는 펑션방식, 메소드방식 2가지
## dir a에 split 없다.

In [63]:
np.split(a,(1,2))  ## 튜플형태로 나눈다 0에서 1까지 1에서 2까지 3에서 끝까지 3등분이 된다. axis 0이다
                    # 인덱스 0에서 1 1에서 2 2에서 끝까지

[array([[100,   1,   2,   3,   4,   5,   6,   7,   8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [64]:
np.split(a,(2,2)) ## 2.2구간은 없으니까 빈구간

[array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
        [  9,  10,  11,  12,  13,  14,  15,  16,  17]]),
 array([], shape=(0, 9), dtype=int32),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [65]:
np.split(a,(2,5)) ## 뒷구간은 0

[array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
        [  9,  10,  11,  12,  13,  14,  15,  16,  17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int32)]

In [66]:
np.split(a,(-2,5)) ## 0부터 잘린다 -여도 기준점은 -

[array([[100,   1,   2,   3,   4,   5,   6,   7,   8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int32)]

In [73]:
np.split(a,(5,5), axis=1) 

[array([[100,   1,   2,   3,   4],
        [  9,  10,  11,  12,  13],
        [ 18,  19,  20,  21,  22]]),
 array([], shape=(3, 0), dtype=int32),
 array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

In [77]:
np.split(a,(5,), axis=1) 

[array([[100,   1,   2,   3,   4],
        [  9,  10,  11,  12,  13],
        [ 18,  19,  20,  21,  22]]), array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

In [76]:
np.split(a,(5,), axis=0)  ## vsplit 

[array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
        [  9,  10,  11,  12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23,  24,  25,  26]]),
 array([], shape=(0, 9), dtype=int32)]

In [68]:
## 가운데 구분되는 거 빈리스트 있는거 불편해 ! 이럼 hsplit


In [71]:
np.hsplit(a,(5,))  ## 원소 하나만 쓰면 구분선 없음

[array([[100,   1,   2,   3,   4],
        [  9,  10,  11,  12,  13],
        [ 18,  19,  20,  21,  22]]), array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

In [74]:
np.vsplit(a,(2,))  ## 원소 하나만 쓰면 구분선 없음

[array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
        [  9,  10,  11,  12,  13,  14,  15,  16,  17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [ ]:
## 스플릿 알고있으면  axis 0 1 에따라 h vsplit 쓸수있따.

In [79]:
b = np.arange(5)

In [80]:
c = np.arange(5,10)

In [81]:
np.stack((b,c),1)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [86]:
np.vstack((b,c))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [87]:
np.r_[b,c] ## h_stack이랑 같다 매틀랩에 이런거 있어서 포함시켜 준거다 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
np.c_[b,c] 

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [90]:
np.s_[b,c]  ## 슬라이싱 객체를 만드는거  _ 삼총사  안할거다 ㅈㄴ 헷갈림

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [91]:
[1,2,3,4,5,][slice(1,2)] ## slice 객체를 만들어주는 애가 s_

[2]

In [93]:
[1,2,3,4,5,][0:3]

[1, 2, 3]

In [99]:
np.arange(10)[np.s_[1]]

1

In [101]:
np.s_[1,5]

(1, 5)

In [102]:
###

In [103]:
np.column_stack([b,c]) ## 붙이는거 쪼개는거 중요한 이슈 연산 다양화 아주 다양한 애들이 존재
                        ## 이시스템 지속가능 데이터 소스 파이프라이닝 계쏙 지속 가능해야함 엑셀 이용해서 바꾸고 바꾸고 하면 out 자동화 시켜야 한다
                        ## 엑셀로 변화시켜서 하면 존나 노가다 귀찮다.
                        ## 시스템 기반 예측하는 사람들 시스템 업데이트가 자주 일어남 자동화시켜야함 이런거 필수적으로 사용

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [104]:
a = np.arange(6)

In [106]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [108]:
a = np.array([[0,1,2,3,4,5]])

In [109]:
a

array([[0, 1, 2, 3, 4, 5]])

In [111]:
a[np.newaxis]  ## 차원수가 늘어남

array([[[0, 1, 2, 3, 4, 5]]])

In [112]:
np.newaxis is None

True

In [113]:
## 넘파이에서 이상한 문법 인덱싱대신

In [114]:
a[None] ## 차원이 확대된다.
## None 보기 안좋아서 np.newaxis 이러면 축이 하나 더생긴다.

array([[[0, 1, 2, 3, 4, 5]]])

In [117]:
a = a.reshape(2,3)

In [118]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [119]:
a[np.newaxis]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [120]:
# 원소 각각을 차원화 하고 싶다 하면 
a[:,np.newaxis]


array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [121]:
a[:,:,np.newaxis] ## 맨안에 있는게 차원이 증가 
                    # 모양을 바꿀떄 이렇게 바꿀수가 있다.

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [124]:
a = np.arange(6)

In [125]:
a[:, np.newaxis]  ## 나중에 연산하기 위해서 행렬 모양 같고, 쉐잎에 맞는 연산형태를 맞추기 위해서 쉐잎을 자유자재로 변화 시킬수 있어야 한다.

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [126]:
np.expand_dims(a,0)

array([[0, 1, 2, 3, 4, 5]])

In [127]:
np.expand_dims(a,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [128]:
np.expand_dims(a,2)  ## 느껴봐~ 이거 많이 쓴다.
                    ## 1차원 짜리는 2차원까지만 한계다 차원을 한개씩밖에 못해준다 expand_dims 찐따새끼

C:\Users\legen\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Both axis > a.ndim and axis < -a.ndim - 1 are deprecated and will raise an AxisError in the future.
  """Entry point for launching an IPython kernel.


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
## 넘파이기반 로우레벨부터 만든다면 모양 못바꾸면 연산을 못시킨다. 
## expand dimention 쓰면 된다.

In [130]:
## 3차원 2차원짜리 이미지가 3개 붙어있다고 생각
## 1

array([[[[[[[[0, 1, 2, 3, 4, 5]]]]]]]])

In [131]:
a = np.arange(27).reshape(3,3,3)

In [132]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [136]:
np.swapaxes(a, 0,2) ##축을 0,1,2 이렇게 축도 바꿀수가 있고

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [137]:
np.moveaxis(a, 0,2) ##축을 이동시킬수도 있다.

## 자유자재로 바꾸는게 중요하다. 

array([[[ 0,  9, 18],
        [ 1, 10, 19],
        [ 2, 11, 20]],

       [[ 3, 12, 21],
        [ 4, 13, 22],
        [ 5, 14, 23]],

       [[ 6, 15, 24],
        [ 7, 16, 25],
        [ 8, 17, 26]]])

In [ ]:
## 인덱스 슬라이스 브로드캐스트 뉴펑션, 쉐이프(나중에 연산할려면 모양다 맞춰줘야함 만만치 않음)
# 사용자 데이터 타입정할수 있다. 리스트 형태 
#'rex', 9, 81 햇으면 자동적으로 바꿔줬더니 커스터마이징 마치 디비처럼 쓸수 있다. 컬럼명 name ,age, weight 
#유니코드 int float
# dtype rex는 name u10 9는 age 14 81.0 weight f4 float
## 정형화된 데이터를 만들고 싶을떄 이방식 사용
# https://docs.scipy.org/doc/numpy/user/basics.rec.html?highlight=struc#module-numpy.doc.structured_arrays

In [169]:
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
...              dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])




In [170]:
x

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [149]:
x[0]  ## 디비처럼 쓸수가 있다.

('Rex', 9, 81.)

In [151]:
x[1]

('Fido', 3, 27.)

In [152]:
## 스트럭쳐드 어레이를 통해 판다스가 만들어 졌다.

In [154]:
from collections import namedtuple  ## 딕셔너리 파이썬 유명한 구조

In [155]:
namedtuple # 파이썬에서 타입은 클래스 

<function collections.namedtuple>

In [156]:
Address = namedtuple('Address', ('name', 'age','weight'))

In [159]:
al = Address('Rex',27,81.0)  ## 클래스 만드는거랑 똑같다.(인스터스화) Address 가 클래스 이름

In [160]:
al

Address(name='Rex', age=27, weight=81.0)

In [161]:
al.name

'Rex'

In [162]:
al.age

27

In [165]:
dir(al) #'age','count', 'index', 'name', 'weight'] ## count, index 튜플에 쓰는애 나머지는 어트리뷰트로 들어감
        # 네임드 튜플 써서 빠르게 클래스 만듬
        # 메타클래스 타입쓰면 동적으로 정의안해도 클래스 처럼 쓸수있따.
        ## 튜플에있는 카운트 인덱스 도 쓸수 있따. . 도되고 [0]도 된다.

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '_asdict',
 '_fields',
 '_make',
 '_replace',
 '_source',
 'age',
 'count',
 'index',
 'name',
 'weight']

In [ ]:
dir()

In [166]:
al[0]

'Rex'

In [167]:
al["name"] # 튜플이어서 이건 안됨 딕셔너리만 됨

TypeError: tuple indices must be integers or slices, not str

In [168]:
# 네임드 튜플이 판다스의 스트럭트어레이와 비슷하다 판다스에서 보고 만든거

In [ ]:
# 튜플은 db 튜플 로우개념

In [171]:
x["name"]  ## 행으로도 접근가능 열로도 접근가능

array(['Rex', 'Fido'], dtype='<U10')

In [172]:
x[0]

('Rex', 9, 81.)

In [173]:
## 키로 접근이 되므로 속도가 엄청 빠르다.  디스크가 아니라 메모리에 올리므로 속도가 빠르다
## 인덱스하면 로우 튜플 다가져옴,딕셔너리 방식, 컬럼데이터 다 가져옴

In [174]:
x["name"]

array(['Rex', 'Fido'], dtype='<U10')

In [175]:
x.name

AttributeError: 'numpy.ndarray' object has no attribute 'name'

In [176]:
dir(x)  ## 스트럭쳐드는 클래스 방식으로 못함 . 이거 못함
        ## 네임드는 키방식으로는 안되고
        ## 데이터타입마다 값 추출하는 방식이 다르다.

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

In [177]:
'name' in dir(x)

False

In [ ]:
## 나만의 데이터 구조 만들수 있따.