In [1]:
import numpy as np

### 다양한 numpy Type

In [5]:
np.byte

numpy.int8

In [3]:
np.short

numpy.int16

In [6]:
np.ubyte

numpy.uint8

In [7]:
np.intc

numpy.int32

In [11]:
np.half

numpy.float16

In [12]:
np.single

numpy.float32

In [13]:
np.double

numpy.float64

In [14]:
np.cdouble

numpy.complex128

In [15]:
np.int8

numpy.int8

In [16]:
y = np.int_([1,2,4])

In [17]:
y

array([1, 2, 4])

In [18]:
np.array([1,2,3],dtype='f')

array([1., 2., 3.], dtype=float32)

In [19]:
z = np.arange(3,dtype = np.uint8)

In [20]:
z

array([0, 1, 2], dtype=uint8)

In [21]:
np.array([1,2,3],dtype='f')

array([1., 2., 3.], dtype=float32)

### 형변환

In [31]:
z.astype(float)

array([0., 1., 2.])

In [23]:
np.int8(z)

array([0, 1, 2], dtype=int8)

### dtype 이용

In [32]:
d = np.dtype(int)

In [33]:
d

dtype('int32')

In [35]:
np.issubdtype(d,np.integer)

True

In [36]:
np.issubdtype(d,np.float)

C:\Users\SeoDongUk\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  """Entry point for launching an IPython kernel.


False

### Overflow Errors

In [37]:
np.power(100,8,dtype=np.int64)

10000000000000000

In [38]:
np.power(100,8,dtype=np.int32)

1874919424

In [39]:
np.iinfo(np.int)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [40]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [43]:
np.power(100,100,dtype=np.float64)

1e+200

In [54]:
1+ (np.finfo(np.longdouble).eps)

1.0000000000000002

## Array creation

1. Conversion from other Python structures
2. Intrinsic numpy array creation objects
3. Reading arrays from disk
4. Creating arrays from raw bytes through the use of strings of buffers
5. Use of special library functions

### 1. Conversion

In [59]:
x = np.array([[1,2.0],[0,0],[1+1j,3.]])
x

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

### 2. Intrinsic creation

In [61]:
np.arange(2,10,dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [62]:
np.arange(2,3,0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [63]:
np.linspace(1.,4.,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [77]:
np.indices((2,2))

array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [0, 1]]])

## Indexing

In [78]:
x = np.arange(10)

In [80]:
x.shape = (2,5)

In [82]:
x[-1,-1]

9

In [83]:
x[0]

array([0, 1, 2, 3, 4])

In [84]:
x = np.arange(10)

In [85]:
x[2:5]

array([2, 3, 4])

In [86]:
x[:-7]

array([0, 1, 2])

In [89]:
y = np.arange(35).reshape(5,7)

In [91]:
y[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

In [92]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [98]:
x = np.arange(10,1,-1)

### Index arrays

In [99]:
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [100]:
x[np.array([3,3,1,8])] # array로 index가능하다.

array([7, 7, 9, 2])

In [102]:
x[[3,3,1,8]]

array([7, 7, 9, 2])

In [104]:
x[np.array([[1,1],[2,3]])]

array([[9, 9],
       [8, 7]])

In [105]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [107]:
y[[0,2,4],[0,1,2]]

array([ 0, 15, 30])

In [108]:
y[[0,2,4],1]

array([ 1, 15, 29])

In [111]:
y[:,[0,2,4]]

array([[ 0,  2,  4],
       [ 7,  9, 11],
       [14, 16, 18],
       [21, 23, 25],
       [28, 30, 32]])

### Boolean or mask index arrays

In [207]:
b = y>20

In [208]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [209]:
y[b] # boolean으로 index시에는 1-D array가 나온다.

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [210]:
np.nonzero(b)

(array([3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6], dtype=int64))

In [115]:
y[np.nonzero(b)]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [130]:
np.nonzero(b)


(array([3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6], dtype=int64))

In [136]:
b[:,5]

array([False, False, False,  True,  True])

In [134]:
y[b[:,5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [137]:
x = np.arange(30).reshape(2,3,5)

In [138]:
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [139]:
b = np.array([[True,True,False],[False,True,True]])

In [140]:
x[b]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

### Combining index arrays with slices

In [142]:
y[np.array([0,2,4]),1:3]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [146]:
y[[0,2,4]]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [165]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [150]:
b = y>20

In [151]:
y[b[:,5],1:3]

array([[22, 23],
       [29, 30]])

### Structural indexing tools

In [167]:
y.shape
y[:,np.newaxis,:]

array([[[ 0,  1,  2,  3,  4,  5,  6]],

       [[ 7,  8,  9, 10, 11, 12, 13]],

       [[14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27]],

       [[28, 29, 30, 31, 32, 33, 34]]])

In [152]:
x = np.arange(5)

In [153]:
x[:,np.newaxis] + x[np.newaxis,:]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [155]:
x[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [156]:
x[np.newaxis,:]

array([[0, 1, 2, 3, 4]])

In [158]:
z = np.arange(81).reshape(3,3,3,3)

In [162]:
z

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [163]:
z[1,...,2]

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

In [164]:
z[1,:,:,2]

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

### Assigning values to indexed arrays

In [168]:
x = np.arange(10)

In [170]:
x[2:7] = 1
x

array([0, 1, 1, 1, 1, 1, 1, 7, 8, 9])

In [173]:
x[2:7] = np.arange(5)
x

array([0, 1, 0, 1, 2, 3, 4, 7, 8, 9])

In [172]:
x

array([0, 1, 0, 1, 2, 3, 4, 7, 8, 9])

In [177]:
x[1] = 1.2

In [175]:
x

array([0, 1, 0, 1, 2, 3, 4, 7, 8, 9])

In [179]:
x = np.arange(0,50,10)
x

array([ 0, 10, 20, 30, 40])

In [181]:
x[np.array([1,1,3,1])] += 1 
# x[1]+1이 3번 assign x[1]에 되는 것이지, 3이 오르는게 아니다.

In [182]:
x

array([ 0, 11, 20, 31, 40])

### Dealing with variable numbers of indices within programs

In [184]:
indices = (1,1,1,1)
z[indices]

40

In [188]:
indices = (1,Ellipsis,1)
z[indices]

array([[28, 31, 34],
       [37, 40, 43],
       [46, 49, 52]])

# Broadcasting

- Vectorizing이 일어난다.
- Two dimensions are compatible when they are equal or one of them is 1

In [216]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))

In [217]:
x.shape

(4,)

In [218]:
y.shape

(5,)

In [220]:
x+y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [221]:
xx.shape

(4, 1)

In [223]:
xx

array([[0],
       [1],
       [2],
       [3]])

In [224]:
y

array([1., 1., 1., 1., 1.])

In [222]:
xx+y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [225]:
x.shape, z.shape

((4,), (3, 4))

In [226]:
z

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [227]:
x+z

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [228]:
x

array([0, 1, 2, 3])

In [229]:
a = np.array([0.0,10.0,20.0,30.0])
b = np.array([1.0,2.0,3.0])

In [232]:
a[:,np.newaxis].shape , b.shape

((4, 1), (3,))

In [236]:
# Outer product
a[:,np.newaxis] * b

array([[ 0.,  0.,  0.],
       [10., 20., 30.],
       [20., 40., 60.],
       [30., 60., 90.]])

# Structured arrays 

In [237]:
x = np.array([('Rex',9,81.0),('Fido',3,27.0)],
            dtype = [('name','U10'),('age','i4'),('weight','f4')])

In [238]:
x

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [241]:
x['name']

array(['Rex', 'Fido'], dtype='<U10')

### Structured Datatype Creation

In [249]:
# First, a list of tuples
np.dtype([('x','f4'),('y',np.float32),('z','f4',(2,2))])

dtype([('x', '<f4'), ('y', '<f4'), ('z', '<f4', (2, 2))])

In [262]:
np.dtype([('x','f4'),('','i4'),('z','i8')])

dtype([('x', '<f4'), ('f1', '<i4'), ('z', '<i8')])

In [252]:
# Second, a string of comma-separated dtype specifications
np.dtype('i8,f4,S3')

dtype([('f0', '<i8'), ('f1', '<f4'), ('f2', 'S3')])

In [253]:
np.dtype('3int8, float32, (2, 3)float64')

dtype([('f0', 'i1', (3,)), ('f1', '<f4'), ('f2', '<f8', (2, 3))])

In [254]:
# Third, a dictionary of field parameter arrays
np.dtype({'names': ['col1', 'col2'], 'formats': ['i4', 'f4']})

dtype([('col1', '<i4'), ('col2', '<f4')])

In [255]:
np.dtype({'names': ['col1', 'col2'],
           'formats': ['i4', 'f4'],
           'offsets': [0, 4],
           'itemsize': 12})

dtype({'names':['col1','col2'], 'formats':['<i4','<f4'], 'offsets':[0,4], 'itemsize':12})

In [286]:
# Fourth, a dictionary of field names
np.dtype({'col1': ('i1', 0), 'col2': ('f4', 1)})

dtype([('col1', 'i1'), ('col2', '<f4')])

In [256]:
d = np.dtype([('x','i8'),('y','f4')])

In [260]:
d.names

('x', 'y')

In [277]:
d.fields

mappingproxy({'x': (dtype('int64'), 0), 'y': (dtype('float32'), 8)})

In [278]:
def print_offsets(d):
    print("offsets:",[d.fields[name][1] for name in d.names])
    print('itemsize:',d.itemsize)

In [282]:
print_offsets(np.dtype('u1,u1,i4,u1,i8,u2',align=True))
# if align is True, structure will be padded as C way

offsets: [0, 1, 4, 8, 16, 24]
itemsize: 32


### Field Titles

In [283]:
np.dtype([(('my title','name'),'f4')])

dtype([(('my title', 'name'), '<f4')])

In [294]:
np.dtype({'name':('i4',0,'my title')})

dtype([(('my title', 'name'), '<i4')])

In [292]:
for name in d.names:
    print(d.fields[name][:2])

(dtype('int64'), 0)
(dtype('float32'), 8)


### Assigning data to a structured Array

- Assignment from Python Native Types (tuples)

In [296]:
x = np.array([(1,2,3),(4,5,6)],dtype='i8,f4,f8')

In [300]:
x[1] = (7,8,9)

In [301]:
x

array([(1, 2., 3.), (7, 8., 9.)],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '<f8')])

- Assignment from Scalars

In [302]:
x = np.zeros(2,dtype='i8,f4,?,S1')

In [304]:
x[:] = 3

In [305]:
x

array([(3, 3.,  True, b'3'), (3, 3.,  True, b'3')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [306]:
x[:] = np.arange(2)

In [307]:
x

array([(0, 0., False, b'0'), (1, 1.,  True, b'1')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [309]:
twofield = np.zeros(2, dtype=[('A', 'i4'), ('B', 'i4')])
twofield

array([(0, 0), (0, 0)], dtype=[('A', '<i4'), ('B', '<i4')])

In [320]:
onefield = np.ones(2, dtype=[('A', 'f4')])
onefield

array([(1.,), (1.,)], dtype=[('A', '<f4')])

In [321]:
nostruct = np.zeros(2, dtype='i4')
nostruct

array([0, 0])

In [322]:
nostruct[:] = onefield

- Assignment from other Structured Arrays

In [325]:
a = np.zeros(3, dtype=[('a', 'i8'), ('b', 'f4'), ('c', 'S3')])
b = np.ones(3, dtype=[('x', 'f4'), ('y', 'S3'), ('z', 'O')])

In [326]:
a

array([(0, 0., b''), (0, 0., b''), (0, 0., b'')],
      dtype=[('a', '<i8'), ('b', '<f4'), ('c', 'S3')])

In [327]:
b

array([(1., b'1', 1), (1., b'1', 1), (1., b'1', 1)],
      dtype=[('x', '<f4'), ('y', 'S3'), ('z', 'O')])

In [330]:
b[:] = a

In [331]:
b

array([(0., b'0.0', b''), (0., b'0.0', b''), (0., b'0.0', b'')],
      dtype=[('x', '<f4'), ('y', 'S3'), ('z', 'O')])

### Indexing Structured Arrays

In [361]:
x = np.array([(1,2),(3,4)],dtype=[('foo','i8'),('bar','f4')])

In [362]:
x['foo'] = 10

In [364]:
x

array([(10, 2.), (10, 4.)], dtype=[('foo', '<i8'), ('bar', '<f4')])

In [337]:
y = x['bar'] # It shares same memory locations

In [338]:
y[:] = 11 

In [339]:
x

array([(10, 11.), (10, 11.)], dtype=[('foo', '<i8'), ('bar', '<f4')])

In [347]:
y.dtype, y.shape, y.strides # It is non-structured array

(dtype('float32'), (2,), (12,))

In [365]:
x = np.zeros((2,2),dtype = [('a',np.int32),('b',np.float64,(3,3))])

In [366]:
x

array([[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])],
       [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]],
      dtype=[('a', '<i4'), ('b', '<f8', (3, 3))])

In [367]:
x['b'].shape 
# the dimensions of subarray are appended to the shape of the result

(2, 2, 3, 3)

In [368]:
x['a']

array([[0, 0],
       [0, 0]])

In [369]:
a = np.zeros(3, dtype=[('a', 'i4'), ('b', 'i4'), ('c', 'f4')])

In [377]:
a[['a','c']] = (2,3)

In [378]:
a

array([(2, 0, 3.), (2, 0, 3.), (2, 0, 3.)],
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<f4')])

In [379]:
a[['a','c']] = a[['c','a']] # swaps

In [380]:
a

array([(3, 0, 2.), (3, 0, 2.), (3, 0, 2.)],
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<f4')])

In [381]:
x = np.array([(1,2.,3.)],dtype='i,f,f')

In [383]:
scalar = x[0]

In [385]:
scalar # Structured scalar

(1, 2., 3.)

In [387]:
x = np.array([(1, 2), (3, 4)], dtype=[('foo', 'i8'), ('bar', 'f4')])

In [388]:
s = x[0]

In [390]:
s['bar'] = 100

In [391]:
x # structured scalar act like views into the original array

array([(1, 100.), (3,   4.)], dtype=[('foo', '<i8'), ('bar', '<f4')])

In [392]:
scalar = np.array([(1, 2., 3.)], dtype='i, f, f')[0]

In [394]:
scalar.item(), type(scalar.item())

((1, 2.0, 3.0), tuple)

### Structure Comparison

In [396]:
a = np.zeros(2, dtype=[('a', 'i4'), ('b', 'i4')])
b = np.ones(2, dtype=[('a', 'i4'), ('b', 'i4')])

In [397]:
a == b

array([False, False])