이게 없었으면 파이썬에서 데이터 분석 못했을 것.

파이썬은 속도 관점에서 느렸다.

요즘에는 GPU를 사용하거나 여러대 컴퓨터 연결해서 분산 처리하면됨.

파이썬을 컴파일 하여 속도를 줄임. Cython, Shed Skin, Numba, Pythran, PyPy

PyPy : 파이썬의 단점인 동적, 스택, 등등을 최적화 시켜서 5배정도 빠름. 문법 수정할 필요 없음. 호환성 문제가 있음.

어떤 부분이 병목현상이 일어날 수 있음. 그 부분에 다른 언어를 사용할 수 있음.

## numpy
+ 편하고 쉽다
+ 빠르다.
    + 효율 적인 자료구조 : 메모리 연속적, stride를 이용해 다양하게 사용
    + 호모 지니어스적인 구조
+ numpy는 가장 하위 모델임. 판다스, 파이토치, 텐서 플로우, 사이킷런을 numpy로 만듬.
+ vectorization을 사용함.


vectorization : 벡터화 시킴.
+ 행렬을 쓰는 이유는 한번에 여러개의 수를 계산할 수 있음.
+ 넘파이는 gpu를 지원하지 않음.
+ 루프를 안씀.
+ 무조건 쓰는 거는 아님. 크기가 작으면 순수 파이썬 구현보다 낮은 성능을 가짐
+ 모든 데이터 처리를 한번만 해줌.

+ 1차원은 vector
+ 2차원은 Matrix
+ 3차원은 3D array(3rd order Tensor)
+ N차원 은 ND array

#### 어떤 현상을 벡터로 만드는게 핵심

In [1]:
import numpy as np

In [3]:
dir(np) # 대문자로 이뤄져있으면 상수처럼 쓴다.

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

리터럴, 인스턴스화, 인스턴스화 하지 않고 다른 함수의 힘을 빌려서 인스턴스화 하는 걸 팩토리 메소드.

Homogenious : range, str 3총사, array
1. 다음 데이터 타입이 뭐가올지 체크할 필요 없음.
2. 속도가 빠름.
3. 파이썬 공식 arary는 느려서 안씀. 

In [4]:
a = np.array()

C로 저장하는 방식과 포트란으로 저장해주는 방식을 선택할 수 있음.

_ like

In [12]:
a = np.array((1,2))

In [14]:
a # 튜플로넣으면 리스트로 바뀜. 뮤터블 속성을 가짐

array([1, 2])

뮤터블에서 나오는 문제점 다 가지고 있음.
1. 값 함부로 바꾸면 안됨.
2. 스왈로우 카피 딥 카피 조심

In [15]:
type(a) # n차원 array

numpy.ndarray

In [16]:
a = np.array([[1,2],[3,4]])

In [17]:
a

array([[1, 2],
       [3, 4]])

In [18]:
a = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])

In [19]:
a

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

사각형이 여러가지 있다고 이해하면 쉬움

In [20]:
type(a)

numpy.ndarray

In [24]:
n = np.ndarray(0)

In [25]:
n

array([], dtype=float64)

In [29]:
a = np.array(['1',2,3])

저장하는 방식이 <이면 리틀엔디언 방식

In [30]:
a

array(['1', '2', '3'], dtype='<U1')

호모지니어스라서 어떤 데이터 타입으로 바꿔줌.

In [28]:
a = np.ndrarray([0,'1'])

AttributeError: module 'numpy' has no attribute 'ndrarray'

인스턴스 만드는거 3가지
1. 클래스 인스턴스화
2. 리터럴 방식
3. 팩토리 메서드는 인스턴스화를 편리하게 해줄려고 매핑해줌

vars : 값을 한개만 가짐, __ dict __ attribute

In [32]:
a = np.array([[1,2],[3,4]])

In [33]:
a

array([[1, 2],
       [3, 4]])

In [34]:
a.ndim # 차원을 알수 있음

2

In [38]:
a.shape # 몇행 몇열인지 알 수 있음. 모양 맞추는데 굉장히 중요함.

(2, 2)

In [41]:
a.flags # 저장 방식을 보여줌. C방식인가 F 방식인가

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

C 방식은 연속적으로 1,2,3,4

F 방식은 1,3,2,4 밑으로 간다.

In [43]:
a.size # 원소의 개수

4

In [45]:
a.itemsize #  각 하나의 원소가 몇 비트인가

4

In [46]:
a.dtype # 데이터 타입

dtype('int32')

In [47]:
b = np.array([[1,2],[3,4]])

In [48]:
x = [1,2,3,4]
y = [2,3,4,5]

In [49]:
x+y # 뒤에 추가됨.

[1, 2, 3, 4, 2, 3, 4, 5]

In [50]:
a + b # numpy 구조는 각각 원소끼리 계산해줌.

array([[2, 4],
       [6, 8]])

In [51]:
[a+b for a,b in zip(x,y)]

[3, 5, 7, 9]

In [52]:
a - b

array([[0, 0],
       [0, 0]])

In [53]:
a*b

array([[ 1,  4],
       [ 9, 16]])

In [54]:
a/b

array([[1., 1.],
       [1., 1.]])

element-wise : 수학적인 공식을 간단하게 해줌으로서 넘파이가 편하다

In [55]:
a.T # 행과 열을 바꿔줌.

array([[1, 3],
       [2, 4]])

In [57]:
a.strides

(8, 4)

C 는 (8,4), F 는 (4,8)

statsmodel : R 

scikit-image : 이미지 처리를 위한 패키지

scikit-learn

pandas

matplotlib : 그래프

##### ndarray 
+ 맨처음에 header안에 data-type을 보고 가져올 곳을 바로 점프하여 간다.
+ header의 strides는 12,4이면 한열이 3개씩 보여줌. -> 내부구조는 1열

### 쉬운 이유
+ Data Types
    + 쉽게 다양한 타입을 한개로 통일 시켜줄 수 있음.

In [63]:
a = np.array([[1,2],[3,4]], dtype = 'u2') # dtype 단축 표현 사용 가능

In [64]:
a

array([[1, 2],
       [3, 4]], dtype=uint16)

In [66]:
len(np.sctypeDict) # numpy 버전에 따라 개수가 다름.

152

_ 종류
1. 앞에 _ 한개 붙을때는 관례상 private로 씀, from * 붙어있을때 _ 붙어있는거 import 안됨,
2. 앞에 _ 두개 붙을때는 oop할때 이름이 맹글리 됐다.
3. 앞뒤로 _ 두개 : 메직 메소드 
4. _ 가 맨
5. _ 가 한개붙고 이름짓는 경우 다국어 처리 할때사용
6. 이름뒤에 _ 붙어있으면 관례상 파이썬 키워드하고 이름 같을때, 충돌을 피하기 위해 사용.

#### axis
1. 행끼리 계산하는 건 axis = 0
2. 열끼리 계산하는 건 axis = 1

(10,3) 일때 axis = 0 이면 ( ,3) 3개

(10,3) 일때 axis = 1 이면 (10, ) 10개

In [68]:
a = np.arange(10)

In [69]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a.reshape(2,5) # 메모리 공유가 아니라 카피 개념이라서 재할당해야함.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [71]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
a = a.reshape(2,5) # 메모리 공유가 아니라 카피 개념이라서 재할당해야함.

In [75]:
a.sum(axis = 0)

array([ 5,  7,  9, 11, 13])

In [77]:
a.mean(axis = 1)

array([2., 7.])

In [84]:
%time sum(range(1000000000))

Wall time: 38.1 s


499999999500000000

In [85]:
%time np.sum(np.arange(1000000000))

Wall time: 7.31 s


-1243309312

### 데이터 만들기

In [86]:
a = np.zeros((3,4))

In [87]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [88]:
a = np.ones((3,4))

In [89]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [90]:
c = np.full((3,4),3)

In [91]:
c

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [94]:
d = np.ones_like(a) # _like로 하면 a하고 똑같은데 다 1로 만들어줌

In [93]:
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [95]:
b = np.eye(3)  # 단위 행렬

In [96]:
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [97]:
c = np.identity(3) # 단위행렬을 만드는데 옵션없이 빠르게 만들 수 있음.

In [98]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [99]:
f = np.tri(3) # 삼삼각행렬

In [100]:
f

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [102]:
np.transpose(a) # 전체 행렬

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [103]:
d = np.linspace(0,100) # arange랑 비슷하지만 구간별로 짤라서 만들 수 잇음.

In [104]:
d

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [105]:
e = np.logspace(1,100) # 로그로 잘라줄 수 있음.

In [106]:
e

array([1.00000000e+001, 1.04811313e+003, 1.09854114e+005, 1.15139540e+007,
       1.20679264e+009, 1.26485522e+011, 1.32571137e+013, 1.38949549e+015,
       1.45634848e+017, 1.52641797e+019, 1.59985872e+021, 1.67683294e+023,
       1.75751062e+025, 1.84206997e+027, 1.93069773e+029, 2.02358965e+031,
       2.12095089e+033, 2.22299648e+035, 2.32995181e+037, 2.44205309e+039,
       2.55954792e+041, 2.68269580e+043, 2.81176870e+045, 2.94705170e+047,
       3.08884360e+049, 3.23745754e+051, 3.39322177e+053, 3.55648031e+055,
       3.72759372e+057, 3.90693994e+059, 4.09491506e+061, 4.29193426e+063,
       4.49843267e+065, 4.71486636e+067, 4.94171336e+069, 5.17947468e+071,
       5.42867544e+073, 5.68986603e+075, 5.96362332e+077, 6.25055193e+079,
       6.55128557e+081, 6.86648845e+083, 7.19685673e+085, 7.54312006e+087,
       7.90604321e+089, 8.28642773e+091, 8.68511374e+093, 9.10298178e+095,
       9.54095476e+097, 1.00000000e+100])

In [110]:
e = np.empty((4,2)) # C에서 쓰레기 값들어가는 거랑 똑같음. 초기화 되지 않는 값이 들어감
e

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 6.18570189e-321],
       [2.07955588e-312, 2.33419537e-312]])

### 특정 데이터 추출

인덱스하고 키로 뽑을 수 잇음.

In [111]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [112]:
a[1][3] # 파이썬 방식

8

In [113]:
a[1,3] # numpy 방식

8

In [114]:
a[:,3]

array([3, 8])

In [118]:
a = np.arange(27). reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [122]:
a[1,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [126]:
a[1,...] # ...는 전부다.

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [129]:
a[:,:,1]

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [130]:
a = np.arange(10)

In [134]:
a[(a>3) & (a<8)] # 조건을 넣을 수 있음.

array([4, 5, 6, 7])

In [135]:
a[[True,False,True,True,True,True,True,True,True,True]] # 마스킹 기법

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
a>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

##### Fancy Indexing 
열 뽑을 때 아주 쉽게 뽑을 수 있음.

In [138]:
a = np.arange(27).reshape(3,3,3)

In [139]:
a[[1,2]]

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [140]:
a = np.arange(10).reshape(5,2)

In [144]:
a[[1,3]]

array([[2, 3],
       [6, 7]])

In [149]:
a = np.arange(25).reshape(5,5)

In [150]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [151]:
a[0]

array([0, 1, 2, 3, 4])

In [152]:
a[1,3:5]

array([8, 9])

In [153]:
a[:,4]

array([ 4,  9, 14, 19, 24])

In [154]:
a[-2:,-2:]

array([[18, 19],
       [23, 24]])

In [155]:
a[2::2, ::2]

array([[10, 12, 14],
       [20, 22, 24]])

In [156]:
mask = np.array([0,1,0,0,1], dtype=np.bool)

In [157]:
a[mask,1]

array([ 6, 21])

In [158]:
b = np.nditer(a)

In [188]:
next(b)

StopIteration: 

In [189]:
def add_(a,b):
    return a+b

In [190]:
x = np.arange(5)
y = np.arange(5)

In [197]:
x+3 #  np.arange는 +가 됨. list는 안됨. 이런 기법을 브로드 캐스팅이라 함. 숫자,크기가 안맞지만 간단한 크기는 알아서 맞춰줌.

array([3, 4, 5, 6, 7])

##### ufunc
universial func : 범용적으로 쓸 수 있는 함수, 리스트 같이 여러개도 되고, 한개도 됨.

In [199]:
np.abs([-1,2,-1])

array([1, 2, 1])

In [200]:
np.ceil([2.9,1,2,3,0.3])

array([3., 1., 2., 3., 1.])

In [202]:
np.info(np.ceil)

ceil(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the ceiling of the input, element-wise.

The ceil of the scalar `x` is the smallest integer `i`, such that
`i >= x`.  It is often denoted as :math:`\lceil x \rceil`.

Parameters
----------
x : array_like
    Input data.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
y : ndarray or scalar
    The ceilin

In [203]:
from scipy.special import factorial

In [205]:
factorial([3,4,5,6])

array([  6.,  24., 120., 720.])

In [206]:
np.info(factorial) # scipy도 numpy로 만들어졌다.

 factorial(n, exact=False)

The factorial of a number or array of numbers.

The factorial of non-negative integer `n` is the product of all
positive integers less than or equal to `n`::

    n! = n * (n - 1) * (n - 2) * ... * 1

Parameters
----------
n : int or array_like of ints
    Input values.  If ``n < 0``, the return value is 0.
exact : bool, optional
    If True, calculate the answer exactly using long integer arithmetic.
    If False, result is approximated in floating point rapidly using the
    `gamma` function.
    Default is False.

Returns
-------
nf : float or int or ndarray
    Factorial of `n`, as integer or float depending on `exact`.

Notes
-----
For arrays with ``exact=True``, the factorial is computed only once, for
the largest input, with each other result computed in the process.
The output dtype is increased to ``int64`` or ``object`` if necessary.

With ``exact=False`` the factorial is approximated using the gamma
function:

.. math:: n! = \Gamma(n+1)

Examples


In [211]:
np.where(a>5, 0, 1) # 조건을 쓸 때, a가 5보다크면 0으로 바꾸고 아니면 1로 바꿔라.

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [212]:
a[np.where(a>5)] # 그냥쓰면 조건을 만족하는 인덱스를 알려줌.

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [213]:
np.max(a) # 가장 큰수를 나오게 한다.

24

In [214]:
np.argmax(a) # 가장큰수를 나타내는 인덱스를 알려줌.

24

In [215]:
np.argmin(a)

0

In [216]:
a.argmin()

0

In [217]:
from numpy import pi
from math import pi as mpi

In [218]:
pi == mpi

True

In [220]:
dir(...) # 실수 제일 많이 함.

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [221]:
np.nan # float에서 보았음.

nan

In [223]:
float('nan') == np.nan

False

In [225]:
t = float('nan')

float('nan') : nan, 무한대

In [228]:
np.newaxis == None

True

행렬 * 는 원소끼리의 곱

행렬 @ 는 행렬 곱 (numpy에서 만들어달라고 부탁해서 만들어줌.)

.dot 은 내적 개념인데, 행렬 곱

In [229]:
np.exp(a) # 자연 로그

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
        1.78482301e+08],
       [4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
        2.64891221e+10]])

, ... 마스킹 기법 조건 fancy

In [230]:
a = np.arange(10).reshape(2,5)

In [232]:
b = a

In [233]:
a[0][0]= 100
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [234]:
b

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [239]:
c = b.copy() # 파이썬은 스왈로우 카피, numpy는 딥 카피

In [236]:
b[0][0] = -100

In [237]:
b

array([[-100,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [238]:
c

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [240]:
c = b.view() # 스왈로우 카피

In [241]:
b[0][0] = 2100

In [242]:
b

array([[2100,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [ ]:
c

# 과제 : Quickstart tutorial 링크 정리해서 자기만의 노트 만들기