브로드 캐스팅은 복잡한 구조에서는 자동적으로 모양을 못맞춰줌.

In [1]:
import numpy as np

In [5]:
np.lookfor('* array') # 관련된거 다알려줌.

Search results for '* array'
----------------------------
numpy.exp
    Calculate the exponential of all elements in the input array.
numpy.cbrt
    Return the cube-root of an array, element-wise.
numpy.exp2
    Calculate `2**p` for all `p` in the input array.
numpy.fmax
    Element-wise maximum of array elements.
numpy.fmin
    Element-wise minimum of array elements.
numpy.modf
    Return the fractional and integral parts of an array, element-wise.
numpy.rint
    Round elements of the array to the nearest integer.
numpy.sqrt
    Return the non-negative square-root of an array, element-wise.
numpy.expm1
    Calculate ``exp(x) - 1`` for all elements in the array.
numpy.isnan
    Test element-wise for NaN and return result as a boolean array.
numpy.isnat
    Test element-wise for NaT (not a time) and return result as a boolean array.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, ele

In [6]:
a = np.array(100) # 0차

In [7]:
a

array(100)

In [8]:
a = np.array([100]) # 1차

In [9]:
a

array([100])

In [10]:
a = np.array([[1,2,3],[4,5,6]]) # 2차

In [11]:
a

array([[1, 2, 3],
       [4, 5, 6]])

리덕션 : 여러개 값을 한개로 줄임.

strides 개념이 숨어있기 때문에 빠르게 됨.

In [36]:
a = np.arange(27)

In [13]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [ ]:
a.reshape() # 모양을 바꿔줌

In [14]:
a.shape # 튜플로 표현했기때문에 ,를 해줌.

(27,)

In [15]:
a.reshape(4,6)

ValueError: cannot reshape array of size 27 into shape (4,6)

In [18]:
b = a.reshape(3,9) # 뮤터블 함수가 아니기 때문에 자기 자신이 안바뀜. 꼭 재할당 시켜야함.

In [19]:
b[0][0] = 100 

In [21]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26])

reshape 는 참조를 가지고 있기 때문에 copy 해야한다.

In [25]:
b = a.reshape(3,9).copy()

In [26]:
b[0][0] = 100

In [27]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [28]:
b = a.reshape(3, -1) # - 마이너스를 넣으면 auto라는 뜻 9로 바뀜.

In [29]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [30]:
b = a.reshape(-1,9)

In [31]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

마이너스를 두개 쓸 순 없음.

In [33]:
a.resize((3,9)) # 뮤테이블 함수, 재할당안해도 바뀜.

In [34]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [37]:
a.resize((3,5)) # 개수를 안맞춰도 됨

In [38]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
a = np.arange(27)

In [45]:
a.resize((3,10))

In [46]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26,  0,  0,  0]])

In [47]:
a.resize((-1,10)) # 마이너스는 허용하지 않음.

ValueError: negative dimensions not allowed

hsplit : 수평축으로 배열 분할

vsplit : 수직축으로 배열 분할

In [62]:
a = np.arange(27)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [63]:
a = a.reshape(3,9)

In [51]:
'split' in dir(a)

False

In [64]:
np.split(a, (1,2)) # 0~1까지, 1에서 2까지, 2에서 끝까지.

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [65]:
np.split(a, (1,2,3,4)) 

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int32),
 array([], shape=(0, 9), dtype=int32)]

In [66]:
np.split(a, (2,2))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([], shape=(0, 9), dtype=int32),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [69]:
np.split(a, (-1,5)) # 기준이 0

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int32)]

In [70]:
np.split(a, (-2,5)) # 기준이 0

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int32)]

In [73]:
np.split(a, (5,5), axis=1) # axis =1

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]),
 array([], shape=(3, 0), dtype=int32),
 array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

In [74]:
np.hsplit(a,(5,))

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]), array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

In [75]:
np.vsplit(a,(2,))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

### 배열을 붙이는 거

In [76]:
b = np.arange(5)

In [78]:
c = np.arange(5,10)

In [80]:
np.stack((b,c), axis = 1)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [81]:
np.hstack((b,c))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
np.vstack((b,c))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [84]:
np.r_[b,c] # 매틀랩에 이런게 있음.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
np.c_[b,c] # 매틀랩에 이런게 있음.

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [88]:
np.arange(10)[np.s_[1]] # 슬라이싱 하는데 사용

1

In [87]:
[1,2,3,4,5,][slice(1,5)] # [1:5]

[2, 3, 4, 5]

In [89]:
np.column_stack([b,c])

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

데이터 조작하기 편함, 파이프라인 만들어서 자동화 시켜야함. 시스템기반 업데이트 하는 사람들은 잘 사용해야함

In [95]:
a = np.arange(6)

In [96]:
a

array([0, 1, 2, 3, 4, 5])

In [92]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [93]:
a = np.array([[0,1,2,3,4,5]])

In [94]:
a

array([[0, 1, 2, 3, 4, 5]])

In [97]:
a[np.newaxis] # []한개 더 붙임.

array([[0, 1, 2, 3, 4, 5]])

##### np.newaxis
None이지만 새롭게 축을 생성해줄수 있다.

In [98]:
np.newaxis is None

True

In [99]:
a[None]

array([[0, 1, 2, 3, 4, 5]])

In [101]:
a = a.reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [103]:
a[np.newaxis]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [104]:
a[:,np.newaxis]

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [105]:
a[:,:,np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [106]:
a = np.arange(6)

In [108]:
a[:,np.newaxis] # 나중에 연산하기 위해서 shape이 같아야하는데 바꿔줘야함.

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [109]:
np.expand_dims(a,1) # expand_dims이라는 메소드가 있음.

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [110]:
np.expand_dims(a,2) # 차원은 한개 씩 밖에 못해줌. 

C:\Users\seo\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Both axis > a.ndim and axis < -a.ndim - 1 are deprecated and will raise an AxisError in the future.
  """Entry point for launching an IPython kernel.


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [122]:
a = np.arange(27).reshape(3,3,3)

In [123]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [124]:
np.swapaxes(a, 0,1) # 축도 바꿔버림

array([[[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23]],

       [[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26]]])

In [114]:
np.moveaxis(a, 0,2) # 축 이동 가능

array([[[ 0,  9, 18],
        [ 1, 10, 19],
        [ 2, 11, 20]],

       [[ 3, 12, 21],
        [ 4, 13, 22],
        [ 5, 14, 23]],

       [[ 6, 15, 24],
        [ 7, 16, 25],
        [ 8, 17, 26]]])

In [119]:
a = np.arange(30).reshape(2,5,3)

In [120]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [121]:
np.swapaxes(a, 0,2)

array([[[ 0, 15],
        [ 3, 18],
        [ 6, 21],
        [ 9, 24],
        [12, 27]],

       [[ 1, 16],
        [ 4, 19],
        [ 7, 22],
        [10, 25],
        [13, 28]],

       [[ 2, 17],
        [ 5, 20],
        [ 8, 23],
        [11, 26],
        [14, 29]]])

### Structured arrays
이것을 기반으로 판다스를 만듬.

In [129]:
x = np.array([('Rex', 9, 81.0),('Fido', 3, 27.0)], 
             dtype=[('name', 'U10'), ('age','<i4'),('weight','<f4')])

In [130]:
x[1]

('Fido', 3, 27.)

###### namedtuple이랑 비슷

In [131]:
from collections import namedtuple

In [141]:
Addresss = namedtuple('Addresss',('name','age','weight'))

In [142]:
a1 = Addresss('Rex',27,81.0)

In [144]:
dir(a1)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '_asdict',
 '_fields',
 '_fields_defaults',
 '_make',
 '_replace',
 'age',
 'count',
 'index',
 'name',
 'weight']

count와 index는 튜플에 튀어나옴.

In [145]:
a1[0]

'Rex'

In [149]:
x["age"]

array([9, 3])

1. 엑셀은 가상 I/O 기때문에 느림
2. numpy는 메모리에 올리기 때문에 빠름

In [152]:
'name' in dir(x) # 어트리뷰트 방식으로는 접근 못함.

False

In [153]:
x = np.array([('Rex', 9, 81.0),('Fido', 3, 27.0)], 
             dtype=[(0, 'U10'), ('age','<i4'),('weight','<f4')])

TypeError: data type not understood

structured numpy에서는 이름을 숫자로 못넣음.