In [3]:
import pandas as pd

In [4]:
!pip3 install -U scikit-learn

     |████████████████████████████████| 10.5MB 190kB/s eta 0:00:01
     |████████████████████████████████| 286kB 268kB/s eta 0:00:01
  Found existing installation: scikit-learn 0.20.3
    Uninstalling scikit-learn-0.20.3:
      Successfully uninstalled scikit-learn-0.20.3


In [5]:
from sklearn.datasets import load_iris #3가지 종류
# fetch_ : 인터넷에서 가지고 오는 데이터 - 크기가 큼
# load_ : 저장되어 있던 것에서 가지고 오는 데이터 - 크기가 작음
# make_ : 랜덤하게 만들어줌

In [6]:
data = load_iris() # sneak 방식 -> function

In [7]:
data # 넘파이 데이터 즉 얘또 넘파이 기반 # 넘파이 단점 : gpu 지원 안 된다.

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [8]:
# 우리는 다 판다스 기반으로 한다고 했음
# DS에서 판다스가 허브
type(data) # sklearn.utils.Bunch

sklearn.utils.Bunch

Bunch는 관례상 묶음  
즉 데이터 묶음 -> 쪼갤 수 있다  
CS에서 굉장히 많이 쓰는 단어 중 하나

In [9]:
dir(data) # 6개

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [13]:
from pprint import pprint

In [14]:
pprint(data.DESCR)

('.. _iris_dataset:\n'
 '\n'
 'Iris plants dataset\n'
 '--------------------\n'
 '\n'
 '**Data Set Characteristics:**\n'
 '\n'
 '    :Number of Instances: 150 (50 in each of three classes)\n'
 '    :Number of Attributes: 4 numeric, predictive attributes and the class\n'
 '    :Attribute Information:\n'
 '        - sepal length in cm\n'
 '        - sepal width in cm\n'
 '        - petal length in cm\n'
 '        - petal width in cm\n'
 '        - class:\n'
 '                - Iris-Setosa\n'
 '                - Iris-Versicolour\n'
 '                - Iris-Virginica\n'
 '                \n'
 '    :Summary Statistics:\n'
 '\n'
 '    ============== ==== ==== ======= ===== ====================\n'
 '                    Min  Max   Mean    SD   Class Correlation\n'
 '    ============== ==== ==== ======= ===== ====================\n'
 '    sepal length:   4.3  7.9   5.84   0.83    0.7826\n'
 '    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n'
 '    petal length:   1.0  6.9   3.76   1.76    

기본적으로 classification 데이터

data, taget이름, feature이름 나옴

지금부터 판다스로 한다.  
연습용 데이터이지만 다른 데서 랭글링 되어서 가지고 왔다는 가정

In [18]:
iris = pd.DataFrame(data.data, columns = data.feature_names) # data.data는 전체 데이터

In [19]:
iris # 여기서 컬럼을 dimension 또는 feature
# 우리는 랭글링 되었다는 걸 가정
# 공백도 있고 괄호도 있기 때문에 안 좋은 방식

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
5                  5.4               3.9                1.7               0.4
6                  4.6               3.4                1.4               0.3
7                  5.0               3.4                1.5               0.2
8                  4.4               2.9                1.4               0.2
9                  4.9               3.1                1.5               0.1
10                 5.4               3.7                1.5               0.2
11                 4.8               3.4                1.6               0.2
12                 4.8               3.0                1.4               0.1
13                 4.3               3.0                1.1               0.1
14                 5.8               4.0                1.2               0.2
15                 5.7               4.4                1.5               0.4
16                 5.4               3.9                1.3               0.4
17                 5.1               3.5                1.4               0.3
18                 5.7               3.8                1.7               0.3
19                 5.1               3.8                1.5               0.3
20                 5.4               3.4                1.7               0.2
21                 5.1               3.7                1.5               0.4
22                 4.6               3.6                1.0               0.2
23                 5.1               3.3                1.7               0.5
24                 4.8               3.4                1.9               0.2
25                 5.0               3.0                1.6               0.2
26                 5.0               3.4                1.6               0.4
27                 5.2               3.5                1.5               0.2
28                 5.2               3.4                1.4               0.2
29                 4.7               3.2                1.6               0.2
..                 ...               ...                ...               ...
120                6.9               3.2                5.7               2.3
121                5.6               2.8                4.9               2.0
122                7.7               2.8                6.7               2.0
123                6.3               2.7                4.9               1.8
124                6.7               3.3                5.7               2.1
125                7.2               3.2                6.0               1.8
126                6.2               2.8                4.8               1.8
127                6.1               3.0                4.9               1.8
128                6.4               2.8                5.6               2.1
129                7.2               3.0                5.8               1.6
130                7.4               2.8                6.1               1.9
131                7.9               3.8                6.4               2.0
132                6.4               2.8                5.6               2.2
133                6.3               2.8                5.1               1.5
134                6.1               2.6                5.6               1.4
135                7.7               3.0                6.1               2.3
136                6.3               3.4                5.6               2.4
137                6.4               3.1                5.5               1.8
138                6.0               3.0                4.8               1.8
139                6.9     

In [17]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

보통 이 테이블에 target-data까지 있어야 함  
여기는 결과값, labeling data가 없음  
이걸 붙일 것

In [23]:
iris_target = pd.DataFrame(data.target, columns=['target'])

In [24]:
iris_target

target
0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
25        0
26        0
27        0
28        0
29        0
..      ...
120       2
121       2
122       2
123       2
124       2
125       2
126       2
127       2
128       2
129       2
130       2
131       2
132       2
133       2
134       2
135       2
136       2
137       2
138       2
139       2
140       2
141       2
142       2
143       2
144       2
145       2
146       2
147       2
148       2
149       2

[150 rows x 1 columns]

In [22]:
data.target_names # 0: setosa, 1: versicolor, 2: virginica
# 타겟 안에 있는 값의 이름을 뜻함

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [27]:
iris = pd.concat([iris, iris_target], axis=1)

In [28]:
iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
5                  5.4               3.9                1.7               0.4   
6                  4.6               3.4                1.4               0.3   
7                  5.0               3.4                1.5               0.2   
8                  4.4               2.9                1.4               0.2   
9                  4.9               3.1                1.5               0.1   
10                 5.4               3.7                1.5               0.2   
11                 4.8               3.4                1.6               0.2   
12                 4.8               3.0                1.4               0.1   
13                 4.3               3.0                1.1               0.1   
14                 5.8               4.0                1.2               0.2   
15                 5.7               4.4                1.5               0.4   
16                 5.4               3.9                1.3               0.4   
17                 5.1               3.5                1.4               0.3   
18                 5.7               3.8                1.7               0.3   
19                 5.1               3.8                1.5               0.3   
20                 5.4               3.4                1.7               0.2   
21                 5.1               3.7                1.5               0.4   
22                 4.6               3.6                1.0               0.2   
23                 5.1               3.3                1.7               0.5   
24                 4.8               3.4                1.9               0.2   
25                 5.0               3.0                1.6               0.2   
26                 5.0               3.4                1.6               0.4   
27                 5.2               3.5                1.5               0.2   
28                 5.2               3.4                1.4               0.2   
29                 4.7               3.2                1.6               0.2   
..                 ...               ...                ...               ...   
120                6.9               3.2                5.7               2.3   
121                5.6               2.8                4.9               2.0   
122                7.7               2.8                6.7               2.0   
123                6.3               2.7                4.9               1.8   
124                6.7               3.3                5.7               2.1   
125                7.2               3.2                6.0               1.8   
126                6.2               2.8                4.8               1.8   
127                6.1               3.0                4.9               1.8   
128                6.4               2.8                5.6               2.1   
129                7.2               3.0                5.8               1.6   
130                7.4               2.8                6.1               1.9   
131                7.9               3.8                6.4               2.0   
132                6.4               2.8                5.6               2.2   
133                6.3               2.8                5.1               1.5   
134                6.1               2.6                5.6               1.4   
135                7.7               3.0                6.1               2.3   
136                6.3               3.4                5.6               2.4   
137                6.4              

다른 데이터도 판다스로 가져오면 사이킷 쓸 수 있다

data를 가져와서 싸이킷에서 판다스 형태로 쓸 것  
싸이킷은 아주 쉬움 그냥 모델 사용하는 방법  
첫번째 : 알고리즘 불러오기

In [29]:
from sklearn.neighbors import KNeighborsClassifier

이름이 카멜 방식  
-> 데이터 타입이 class  
-> 인스턴스화해야함

In [31]:
knn = KNeighborsClassifier() # parameter에 따라서 모델 성능이 변할 수도 있음
# 모델 셀렉션 관점 수업
# 최적의 모델 찾는다
# 모델 셀렉션이 왜 중요할까?
# 모델마다 특정한 데이터 분포에 성능이 좋은 알고리즘이 있다
# 그것보다 더 중요한 건..

The Unreasonable Effectiveness of Data (2009) - Peter Norvig  
인공지능 1: 현대적 접근방식 <- 전세계에서 가장 많이 팔리는 인공지능 책 (60%이상) - 피터 노빅 <- 구글에 있음  
데이터의 이성적이지 않은..설명 불가능한  
Leargning Curves for Confusion Set Disambiguation (2001) - Michele Banko & Eric Brill  
피터 노빅이 정규식 강좌도 했음 Regex도 중요  
알고리즘별로 실험을 해보면 차이가 남  
알고리즘별로 비교를 했는데 알고리즘보다 데이터의 양이 더 중요했다  
좋은 데이터의 양!  
데이터가 좋으면 알고리즘별로 성능 차이가 별로 크게 나지 않는다  
가정 : 좋은 데이터!  
세상에 좋은 데이터가 별로 없기 때문에 거꾸로 알고리즘이 중요한 것  
좋은 데이터면 알고리즘을 어떤 거 써도 성능이 비슷  
우리가 보는 데이터가 현실을 제대로 반영하지 못하기 때문에 데이터가 많으면 많을수록 좋은 것  
많으면 좋은 데이터일 확률이 많음  
밑에 있는 사람은 2001년에 벌써 냈음  
저사람들은 microsoft사에 있음  
기존에 있는 논문들은 대부분 알고리즘이 중요하다  
andrew ng, logstic regression vs naive bayes  
데이터가 충분하지 않을 때는 특정 구간의 데이터에 따라 성능이 바뀐다  
여기서 제일 중요한 것은 데이터  
수집한 데이터가 현실 세계를 잘 반영하는 좋은 데이터가 아니기 때문에 모델 셀렉션을 잘 해야 함  

1) import
2) import 할 때마다 인스턴스화
3) 학습

싸이킷은 학습시킬 때 fit 사용

In [35]:
knn.fit(iris.iloc[:,:-1], iris[iris.columns[-1]]) # 전부 판다스 집어넣음
# (X, y) 관례상! 학습시킬 때 데이터는 X 네 줄 전체 집어넣음 -> 행렬은 보통 대분자 쓴다 / 벡터는 보통 소문자 쓴다

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [39]:
knn2 = KNeighborsClassifier()

In [40]:
vars(knn2)

{'n_neighbors': 5,
 'radius': None,
 'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'p': 2,
 'n_jobs': None,
 'weights': 'uniform'}

In [41]:
knn2.fit(iris.iloc[:,:-1], iris[iris.columns[-1]])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [42]:
vars(knn2) # 학습시켜서 새로운 객체를 만들었다

{'n_neighbors': 5,
 'radius': None,
 'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'p': 2,
 'n_jobs': None,
 'weights': 'uniform',
 'outputs_2d_': False,
 'classes_': array([0, 1, 2]),
 '_y': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'effective_metric_params_': {},
 'effective_metric_': 'euclidean',
 '_fit_method': 'kd_tree',
 '_fit_X': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
    

In [43]:
# 학습시켰으면 이제부터 예측할 수 있다

In [44]:
knn2.predict([[3,3,3,3]]) # 넘파이 기반
# 그런데 이렇게 사용하면 안 됨

array([1])

In [45]:
data.target_names 

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [46]:
knn2.predict([3,3,3,3])
# ValueError: Expected 2D array, got 1D array instead:
# array=[3 3 3 3].
# Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

ValueError: Expected 2D array, got 1D array instead:
array=[3 3 3 3].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [52]:
knn2.predict([[3,4,1,2]]) # 한개짜리 넘파이는 방향이 없으니까 무조건 2차원 데이터로 넣어야 함
# 방향이 없다 = 행인지 열인지 모른다

array([0])

In [48]:
import numpy as np

In [50]:
a = np.array([1,2,3,4]).reshape(1,4) # 넣으려면 reshape해줘야 함

In [51]:
a # 그래서 아까 knn return의 괄호가 두 개

array([[1, 2, 3, 4]])

In [54]:
knn2.predict_proba([[3,4,1,2]]) # probability 가능성
# 즉 normalization 시킨 값이 나옴

array([[1., 0., 0.]])

In [56]:
knn2.predict_proba([[3,3,3,2]]) # 5 중에 4가 1이라고 예측, 1이 2라고 예측
# 결정자가 하나면 proba 안 나오는 애도 있음

array([[0. , 0.8, 0.2]])

In [57]:
knn2.predict([[3,3,3,2]])

array([1])

In [58]:
# 지금 KNN알고리즘 썼고 K를 5 썼음

In [60]:
!pip3 install mglearn

     |████████████████████████████████| 542kB 160kB/s eta 0:00:01
  Created wheel for mglearn: filename=mglearn-0.1.7-py2.py3-none-any.whl size=582705 sha256=9a9f5eb4939c70be22ec240e0ea789c048e98578111c5eaa0c9d234dff3f5c01
  Stored in directory: /Users/eunha/Library/Caches/pip/wheels/74/cf/8d/04f4932d15854a36726c6210763c7127e62de28f5c8ddfcf3b
Successfully built mglearn


In [61]:
import mglearn

In [62]:
# 모델 셀렉션
# 모델 바꾸기 위해서...
knn2 = KNeighborsClassifier(3)

In [63]:
knn2.fit(iris.iloc[:,:-1], iris[iris.columns[-1]])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [64]:
knn2.predict_proba([[3,3,3,2]])

array([[0., 1., 0.]])

parameter를 바꿀 때마다 예측하는 게 조금씩 달라진다.  
parameter를 가장 좋은 거 찾는 게 모델 셀렉션  
gridsearchcv, randomizesearchcv 방식 사용

In [66]:
knn2.get_params() # 내가 바꿀 수 있는 하이퍼 파라미터

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 3,
 'p': 2,
 'weights': 'uniform'}

주의점 : 모두 성능을 바꾸는데 성능의 종류가 여러가지  
우리가 기본적으로 하는 건 정확도를 이야기함  
n_jobs는 n_이 붙어 있으면 Number of의 뜻이 많다고 했음  
초기값에서 n_jobs = None  
n_jobs는 몇 개의 col을 사용해서 학습시킬 것인가?
보통 n_jobs를 하면 학습이 동시에 여러 개의 col을 쓰니까 빨라짐  
모델은 정확도도 중요하지만 예측 속도도 중요  
예측할 때 시간이 많이 걸리면 사용자 입장에서 안 좋음  
딥러닝은 학습은 오래 걸리지만 예측은 빨리 됨  
n_jobs = -1하면 현재 내가 가진 core 대부분을 써서 최대의 리소스를 가지고 학습시킬 수 있다.

In [71]:
knn2 = KNeighborsClassifier(3, n_jobs=-1)

In [69]:
knn2.fit(iris.iloc[:,:-1], iris[iris.columns[-1]])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=3, p=2,
                     weights='uniform')

In [70]:
knn2.predict_proba([[3,3,3,2]])

array([[0., 1., 0.]])

성능은 정확도뿐 아니라 속도도 포함 <- CS관점

내일도 사이킷  
점심시간 한시반  
시작은 9시반  
발표 시작은 세시  
두시 오십분에는 와 있어야 함  
오늘 팀별 주제, 팀별 자연어 선택 or 딥러닝 선택 보내줘야 함 <- 메일로  
순서 뽑기