In [1]:
# Why Numpy?
# 크게 두가지
# 1) 속도가 빠르고 2) 쉽다
# 1 : C로 만들었고, 효율적인 자료구조
#     이걸 서브클래싱해서 자기만의 데이터 구조를 만듦 <- 세상에 배열로 된 게 엄청 많음 예) 이미지, 영상, 음악
#     그걸 헤더 부분을 읽기 위해서 변경해야 되는 게 많아서 서브클래싱하는 것도 중요한 이슈 중 하나
#     - 벡터라이제이션 <- 굉장히 중요한 이슈

In [2]:
# 모양 변형하는 게 가장 중요
# 1) reshape
# 2) broadcasting (계산할 때 자동적으로 모양 변환 단점 : 복잡한 구조에서는 자동적으로 모양 못 맞춰줌)
# 설명 보는 법
# 1) np.info(여기 궁금한거)
# 2) np.lookfor(여기 궁금한거)

In [3]:
import numpy as np

In [5]:
np.lookfor('create') #create에 관련된 모든 애가 나옴

Search results for 'create'
---------------------------
numpy.array
    Create an array.
numpy.dtype
    Create a data type object.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.nested_iters
    Create nditers for use in nested loops
numpy.bytes0.hex
    B.hex() -> string
numpy.byte.__new__
    Create and return a new object.  See help(type) for accurate signature.
numpy.bool8.__new__
    Create and return a new object.  See help(type) for accurate signature.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.matlib.rand
    Return a matrix of random values with given shape.
numpy.int0.__new__
    Create and return a new object.  See help(type) for accurate signature.
numpy

In [6]:
np.lookfor('shape')

Search results for 'shape'
--------------------------
numpy.shape
    Return the shape of an array.
numpy.reshape
    Gives a new shape to an array without changing its data.
numpy.flip
    Reverse the order of elements in an array along the given axis.
numpy.full
    Return a new array of given shape and type, filled with `fill_value`.
numpy.isin
    Calculates `element in test_elements`, broadcasting over `element` only.
numpy.ones
    Return a new array of given shape and type, filled with ones.
numpy.empty
    Return a new array of given shape and type, without initializing entries.
numpy.zeros
    Return a new array of given shape and type, filled with zeros.
numpy.resize
    Return a new array with the specified shape.
numpy.ndarray
    ndarray(shape, dtype=float, buffer=None, offset=0,
numpy.ndindex
    An N-dimensional iterator object to index arrays.
numpy.squeeze
    Remove single-dimensional entries from the shape of an array.
numpy.ma.shape
    Return the shape of an array.

In [7]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.asarray
    Convert the input to an array.
numpy.ndarray
    ndarray(shape, dtype=float, buffer=None, offset=0,
numpy.recarray
    Construct an ndarray that allows field access using attributes.
numpy.chararray
    chararray(shape, itemsize=1, unicode=Fa

In [8]:
np.lookfor('* array')

Search results for '* array'
----------------------------
numpy.exp
    Calculate the exponential of all elements in the input array.
numpy.cbrt
    Return the cube-root of an array, element-wise.
numpy.exp2
    Calculate `2**p` for all `p` in the input array.
numpy.fmax
    Element-wise maximum of array elements.
numpy.fmin
    Element-wise minimum of array elements.
numpy.modf
    Return the fractional and integral parts of an array, element-wise.
numpy.rint
    Round elements of the array to the nearest integer.
numpy.sqrt
    Return the non-negative square-root of an array, element-wise.
numpy.expm1
    Calculate ``exp(x) - 1`` for all elements in the array.
numpy.isnan
    Test element-wise for NaN and return result as a boolean array.
numpy.isnat
    Test element-wise for NaT (not a time) and return result as a boolean array.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, ele

In [9]:
a = np.array(100)

In [10]:
a # 0차 scala not 1차

array(100)

In [11]:
a = np.array([100])

In [12]:
a # 얘가 1차

array([100])

In [13]:
a = np.array([[1,2,3],[4,5,6]])

In [14]:
a # 2차

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# 여기선 3차까지만 할 거임 (영상 처리 안 함)

In [18]:
a = np.arange(27)

In [19]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [21]:
# 실질적으로 reshape은 비용이 안 든다.
# stride를 이용하기 때문에 변화시키는데에 거의 리얼타임
# 다른 언어에서는 (물론 R에서도 벡터라이징 개념이 있고 stride가 있음)
# reshape하는데 전혀 걱정하지 않고 사용해도 됨.
a.shape # 1차

(27,)

tuple은 한개짜리 할때 ,로 놔야 되니까

In [22]:
a.reshape(4,6) # 개수를 안 맞춰줬기 때문에 ValueError

ValueError: cannot reshape array of size 27 into shape (4,6)

In [24]:
a.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [25]:
# mutable function이 아니기 때문에 자기 자신이 안 바뀐다
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [28]:
a.strides

(8,)

In [29]:
# mutable function일 필요가 없음
# numpy는 연속적인 공간에 저장하고 stride만 바꿔주는 것이기 때문에
b = a.reshape(3,9)

In [30]:
b[0][0] = 100

In [31]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26])

reshape한 걸 b에 저장해줬는데 a도 바뀜!  
이래서 .copy 쓴다

In [35]:
b = a.reshape(3,9).copy() # reshape 쓸 때 이런 거 주의해야 됨

In [36]:
b[0][0] = 200

In [37]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26])

In [38]:
b

array([[200,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [41]:
b = a.reshape(3,-1) # 보통 -1이라고 나올 때는 automatic이라는 뜻

In [42]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [43]:
b = a.reshape(-1,9)

In [45]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [46]:
b = a.reshape(-1,-1) # 두 개 동시에 유추할 수는 당연히 없음 ValueError

ValueError: can only specify one unknown dimension

In [47]:
b = a.reshape(3,-2)

In [48]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [49]:
b = a.reshape(3,-100)

In [50]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

-만 붙으면 알아서 해주는데 관례상 -1 쓴다

In [51]:
# mutable function은 아니지만 데이터를 공유하기 때문에 바꿀 때 주의해야 한다.

In [52]:
# a.resize(new_shape, refcheck=True)
# Change shape and size of array in-place.
a.resize((3,9))

In [53]:
a

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

mutation function 자기 자신이 바뀐다

In [54]:
a. strides

(72, 8)

reshape할 때는 재할당했지만 resize는 mutable function이기 때문에 자기 자신이 바뀌었음  
상황에 따라 다르게 써야 함  
그러니까 두 개 다 알고 있어야 함  
그런데 리사이즈는

In [60]:
a = np.arange(27)

In [61]:
a.resize((3,5))

In [62]:
a # 자동으로 잘려서 나옴!

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [63]:
a = np.arange(27)

In [64]:
a.resize((3,10))

In [65]:
a # 더 크게 만들면 0으로 채워짐

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26,  0,  0,  0]])

In [70]:
a = np.arange(27)

In [67]:
a.resize((-1,10))

ValueError: negative dimensions not allowed

In [68]:
# ValueError: negative dimensions not allowed
# resize는 negative값 허용 안 함
# mutable은 쉽지만 실수할 경우가 너무 많기 때문에 가능하면 안 쓴다
# 그래서 거의 90퍼센트의 책에 reshape이 예제로 나오는 이유

In [72]:
a = a.reshape(3,9)

In [73]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [75]:
'split' in dir(a)

False

In [77]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [82]:
np.split(a,1)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [83]:
np.split(a,2)

ValueError: array split does not result in an equal division

In [80]:
# Signature: np.split(ary, indices_or_sections, axis=0)
np.split(a,(1,2)) # 0에서 1까지, 1에서 2까지, 2에서 끝까지 이렇게 잘라줌

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [81]:
np.split(a,(2,2)) # 0에서 2까지, 2에서 2까지<-얘는 없으니까 빈 list, 2에서 끝까지

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([], shape=(0, 9), dtype=int64),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [84]:
np.split(a,(2,5)) # 0에서 2까지, 2에서 5까지, 5에서 끝까지 <-그런데 얘는 없으니까 없는 게 튀어나온다

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int64)]

In [85]:
np.split(a,(-2,5)) # - 넣으면 0까지 잘림

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int64)]

In [86]:
np.split(a, (5,5), axis=1)

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]),
 array([], shape=(3, 0), dtype=int64),
 array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

In [87]:
# Signature: np.hsplit(ary, indices_or_sections)
np.hsplit(a, 5)

ValueError: array split does not result in an equal division

In [88]:
np.hsplit(a,(5,)) # 한 개만 이렇게 하면 구분선 없어져서 output 나옴

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]), array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

In [89]:
np.vsplit(a, (2,))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [91]:
b = np.arange(5)

In [92]:
c = np.arange(5)

In [93]:
# Signature: np.stack(arrays, axis=0, out=None)
np.stack((b,c))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [94]:
np.stack((b,c),1)

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [95]:
np.hstack((b,c))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [96]:
np.vstack((b,c))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [97]:
np.r_[b,c]

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [98]:
# r_는 함수가 아님 hstack과 똑같음 row
# matlab에 이런 거 있어서 이런 문법이 나옴

In [99]:
np.c_[b,c]

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [100]:
# c는 column

In [101]:
# np.s_
# slicing 객체를 만든다.
# 이거 안 하는 이유?? 헷갈림

In [103]:
[1,2,3,4,5,][slice(1,5)] # slice 객체

[2, 3, 4, 5]

In [104]:
[1,2,3,4,5,][1:5]

[2, 3, 4, 5]

In [106]:
np.arange(10)[np.s_[1]]

1

In [108]:
np.column_stack([b,c])

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

붙이고 쪼개고 모양 변화시키는 건 중요한 이슈 <- 연산 가능하도록 만들기 위함

이거 기억하고 있어야 됨.  
나중에 데이터 모을 때  
엑셀에서 정리해서 save as csv해서 뭐..하면 되긴 하는데  
이걸로 해서 그냥 조작하는 게 훨씬 더 편하다.  
시스템을 만들 때 중요한 것은 이 시스템이 지속가능한가?  
지속 가능하려면 파이프라인 만들어서 수정변경이 쉬워야 함.  
이걸 엑셀로 하면 아웃.  
그래서 자동화 필요.  
시스템 기반으로 예측하는 사람들은 데이터 업데이트가 자주 일어나기 때문에 이런 걸 필수적으로 사용해야 한다.

In [109]:
a = np.arange(6)

In [110]:
a # 1차원

array([0, 1, 2, 3, 4, 5])

In [111]:
a.reshape(6,1) # 2차원

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [113]:
a = np.array([[1,2,3,4,5]])

In [114]:
a #아까 거기서 이런 거 만들고 싶음

array([[1, 2, 3, 4, 5]])

In [115]:
a = np.arange(6)

In [116]:
a[np.newaxis] # np.newaxis 쓰면 []만 하나 더 붙음

array([[0, 1, 2, 3, 4, 5]])

In [117]:
np.newaxis is None

True

In [118]:
a[None] # 차원이 하나 더 확대됨. 원래는 이거였음 그런데 None 하니까 없는 것 같은 느낌이 들어서 np.newaxis라는 걸 정의

array([[0, 1, 2, 3, 4, 5]])

In [119]:
# -> np.newaxis는 새롭게 차원 만드는 애
a = np.arange(6)
a = a.reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [120]:
a[np.newaxis]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [121]:
# 여기서 안에 있는 걸 차원화하고 싶다 하면
a[:,np.newaxis]

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [122]:
a[:,:,np.newaxis] # 맨 안에 있던 게 차원이 증가됨

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

모양을 바꿀 때 이렇게 바꿀 수 있다

In [123]:
a = np.arange(6)

In [124]:
a[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [125]:
# 나중에 연산하기 위해서는 행렬은 기본적으로 shape이 같거나 shape에 맞는 연산형태에 맞추기 위해서 shape을 자유자재로 변형시킬 때 쓰는 애

In [126]:
a = np.arange(6)

In [127]:
np.expand_dims(a,0) # 많이 쓰니까 연산자를 지원해줌

array([[0, 1, 2, 3, 4, 5]])

In [129]:
np.expand_dims(a,1) # 많이 쓰니까 연산자를 지원해줌

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [131]:
np.expand_dims(a,2) # 더 이상 증가시킬 수 없다고 2차원으로 증가시켜줌
# 차원을 한개씩밖에 못 늘려준다.

/Users/eunha/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Both axis > a.ndim and axis < -a.ndim - 1 are deprecated and will raise an AxisError in the future.
  """Entry point for launching an IPython kernel.


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [132]:
np.expand_dims(a,200)

/Users/eunha/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Both axis > a.ndim and axis < -a.ndim - 1 are deprecated and will raise an AxisError in the future.
  """Entry point for launching an IPython kernel.


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [133]:
a = np.arange(27).reshape(3,3,3)

In [134]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [136]:
np.swapaxes(a,0,2) # 축 swap

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [137]:
np.moveaxis(a,0,2) #축을 이동

array([[[ 0,  9, 18],
        [ 1, 10, 19],
        [ 2, 11, 20]],

       [[ 3, 12, 21],
        [ 4, 13, 22],
        [ 5, 14, 23]],

       [[ 6, 15, 24],
        [ 7, 16, 25],
        [ 8, 17, 26]]])

## structured array  
이걸 기반으로 우리가 잘 아는 pandas가 만들어졌다

In [138]:
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)], 
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

In [139]:
x

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [140]:
x[0] # 하나의 DB처럼 사용할 수 있게 된다.

('Rex', 9, 81.)

### namedtuple

In [141]:
from collections import namedtuple

In [142]:
# namedtuple(
#     typename,
#     field_names,
#     *,
#     rename=False,
#     defaults=None,
#     module=None,
# )
Address = namedtuple('Address', ('name', 'age', 'weight'))
# 파이썬에서 type은 class
# 첫번째 데이터가 클래스이름

In [143]:
Address

__main__.Address

In [144]:
a1 = Address('Rex', 27, 81.0) # 클래스의 instance만드는 것과 비슷

In [145]:
a1.name

'Rex'

In [146]:
dir(a1)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '_asdict',
 '_fields',
 '_fields_defaults',
 '_make',
 '_replace',
 'age',
 'count',
 'index',
 'name',
 'weight']

count, index -> tuple에서 있는 것

In [147]:
b = (1,)

In [148]:
dir(b)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

이고 우리가 지정한 age, name, weight가 변수로 들어간 것

파이썬에서 클래스 정의 안해도 된다.  
metaclassm type 쓰면!  
namedtuple 써도 가능  
얘는 tuple에 있는 index, count까지 지원.

In [151]:
a1[0] # index로도 접근 가능

'Rex'

In [152]:
a1['name'] # tuple이기 때문에 안된다

TypeError: tuple indices must be integers or slices, not str

보통 index로 접근할 수 있으면 key로 접근할 수 없다.

namedtuple이 numpy의 structured array와 비슷하다

DB처럼 사용하고 싶을 때 빠르게 만드는 방법

즉 판다스에서 새로 나온 개념이 아님!

numpy의 structured array는 key로도 접근할 수 있다.  
편의상 dictionary방식이라고 부를 것.

In [154]:
x['age'] #key에 있는 column data를 가져온다

array([9, 3], dtype=int32)

즉 2차원으로 행으로도 접근 가능하고 열로도 접근 가능하다

stride 개념 쓰기 때문에 특정 값 뽑아내는 데에 거의 O(1)

싹다 memory에 올림(disk x) -> 더 빠르다

메모리에 다 못 올릴 때 쓰는 애가 다스크..?  
엑셀로도 저거 할 수 있음.  
엑셀은 disk IO기반  
가상메모리 기반이어서 속도가 느릴 수밖에 없는데 얘는 메모리에 올리기 때문에 속도가 엄청나게 빠르다.  
딕셔너리 방식 하면 컬럼 데이터를 다 가져온다.  

In [157]:
x.name # AttributeError: 'numpy.ndarray' object has no attribute 'name'

AttributeError: 'numpy.ndarray' object has no attribute 'name'

In [158]:
dir(x)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [159]:
'name' in dir(x)

False

즉 x는 attribute 방식(?)으로는 접근 못한다.  
그런데 namedtuple은 dictionary 방식으로는 접근 못했다.  
즉 데이터 타입마다 값을 추출하는 방식이 조금씩 다르다.

굉장히 중요한 기법 중 하나  
나만의 데이터 구조를 만들 수 있다.  

In [160]:
# TypeError: data type not understood
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)], 
             dtype=[(0, 'U10'), ('age', 'i4'), ('weight', 'f4')])

TypeError: data type not understood

numpy의 structured array의 문제점은 이름에 무조건 문자열이 들어가야 한다는 것  
그래서 판다스에서는 이름을 숫자로 집어넣을 수 있게 만들어줬음  
그래서 생긴 문제점! 넘파이에서는 인덱스로 접근(예 : x[0])할 수 있었는데 판다스에서는 불가능!  
추가시킬 수도, 합할수도, 나눌 수도, 특정 열을 가지고 올 수도 있음!  
데이터의 정형화, 데이터 분석의 기초 다 이걸로 씀  
가장 밑에 숨어있는 개념의 structured array  
이제 우리가 분석할 형태는 structured array에 기반한다. (결론!)  
내부구조는 structured array라는 걸 기억하고 있어야 함.