# numpy/scipy

numpy...가 없었으면 파이썬에서 데이터 과학을 못했을 것
98년도인가 96년도에 numeric이 제일 처음 나왔음
numeric을 발전시켜서 나온 게 2005년도 numpy
파이썬의 아주 큰 단점? 속도가 느리다!
속도가 느리다는 건 계산 관련해서 엄청나게 단점
속도를 빠르게 하려는 수많은 노력들이 있어왔음
어떻게 하면 될까?
1) 좋은 컴퓨터를 쓰면 됨 그런데 이것도 한계가 있음
- 요즘은 GPU가지고 general purpose라고 해서 일반적인 목적의 GPU를 사용하거나
- parallel computing 여러 대 컴퓨터를 연결해서 사용
-> 돈이 많이 듬!
돈을 안 들이고 어떻게?
2) 파이썬의 언어의 단점을 보완하는 방법으로...
파이썬은 인터프리터 언어. 그런데 파이썬을 컴파일할 수 있음. 제일 유명한 건 Cython - 얘는 자료 형태를 지정해줘야 함 C 속도에 거의 근접하게 나옴 일반적으로 파이썬을 씨보다 빨라봤자 다섯배. 보통은 10~20배. 쟤는 컴파일하기 때문에 속도가 빠름. 요즘에 가장 각광받는 게 PyPy: 파이썬으로 만든 파이썬 속도가 느릴 것 같은데 파이썬의 단점인 다이나믹, stack같은 부분을 최적화시켜서 파이썬보다 다섯배정도 빠름. 얘는 문법 수정할 필요가 없음! PyPy 그대로 파이썬 설치하는 것처럼 설치하면 되는데 아직 서드파이 라이브러리의 호환성 문제가 있긴 함.
3) 어떤 부분이 병목현상이 있는 부분이 있음 Glue Language
태생적으로 C로 만들었고 자바로 만들고 닷넷으로 만드는 등 다른 언어와 잘 붙기 때문에 병목현상이 일어나는 부분에 씨 언어로 짜버림 파이썬은 공식적으로 씨하고 붙일 수 있음 -> 훨씬 더 빨라짐
4) 알고리즘 / 자료구조
똑같은 일을 해도 속도가 차이남.
이런 방법을 이용해서 속도를 빠르게 만들 수 있는데
그 중 계산 관련해서 속도를 빠르게 만든 애가 Numpy!
Numpy는 glue language, data structure 관점에서 속도 향상. 최고 20배까지 속도 빠르게 함.
이 분야에서 속도는 굉장히 민감하고 중요한 문제
우리는 결국 빅데이터 과정이기 때문에 속도가 빠르면 빠를수록 아주 좋음.
numpy 1) 속도 빠르다 2) 편하고 쉽다 (이걸 위해서 다른 걸 배울 필요가 없다)
2번은 어떤 사람에게는 거짓말일 수 있음
아나콘다 <- 예전에는 하나하나 다 설치하거나 했는데 요즘은 아나콘다가 전부 통일시킴
아나콘다를 만든 회사를 만든 사람이 numpy 만든 사람
numpy가 없었으면 파이썬 아마 수업시간에 안 배웠을 것
numpy는 가장 저수준 사실 numpy로 판다스, 사이킷, 텐서플로우, 파이터치를 만듬
굳이 하이레벨 건드리면 되는데 로우레벨까지 건드릴 필요가 없다는 것.
깊게 들어가면 들어갈수록 numpy를 다 해야함
요즘은 책도 numpy부터 시작해서 모든 프레임워크를 다 구현하는 책들이 나오기 시작함
밑바닥부터 시작하는 딥러닝 1,2 <- numpy로 처음부터 다 만들었음
왜 속도가 빠를까? 1)C 2)알고리즘<-?
Vectorization!된 데이터구조
컴파일러 시간에 배울 수 있었던 기법 중 하나
벡터화시킨다.
벡터화?
고등학교 때 행렬 배울 때 왜 행렬 쓴다? 한번에 여러 개의 수를 계산할 수 있다! 이걸 안하면 일일이 하나씩 계산해야 함!
현재 cpu는 벡터 연산을 최적화하도록 지원해줌.
cpu 자체에서 최적화해서 계산해줌.
여기서 궁금해지는 거?
cpu 연산이네? numpy는? cpu지원안함
그래서 tensor만든 것
그 이유는 cpu 지원안했기 대문에 cpu 지원하는 기능을 numpy에 추가
자료구조 시간에 벡터 대신 array라는 표현 많이 사용
array는 CS용어
벡터는 수학적 용어
여러 개의 데이터를 한 묶음으로 만든 애
또 중요한 거? 얘는 for 구문을 돌리지 않음! --> loop가 없다.
loop를 쓰면 속도가 느림.
loop안 쓰기 1) 이터레이터 제너레이터 2) 컴프리헨션 3) 맵필터리듀스 4) 재귀함수
함수형 패러다임에서 나오는 애들은 벡터화와 연관이 있음
함수형 패러다임에서도 for 많이 안 쓴다.
벡터화 기법도 for를 쓰지 않고 연산하는데
for 쓰면 연산의 효율성이 아주 떨어짐.
for 쓰지 않고 벡터를 이용해서 프로그래밍하는 걸 벡터화 또는 array programming이라고 함
array programming이 가장 어려움.....
얘 조금 고생해서 이거 기반으로 뭘 한다고 하면 내 실력이 훨씬 더 높아짐
우리는 얘 좀 많이 할 거임
문제점? 항상 빠른 건 아님. 숫자가 크면 클수록 빨라짐.
작은 범위에서는 array programming이 느릴 수 있음.
무조건 이거 쓰는 건 아니다.
벡터화는 여러 개의 데이터를 하나의 묶음으로 처리하는 애. 얘는 연산을 for 없이 함. (summary)
현대의 cpu는 이걸 연산하는 것까지 최적화된 연산을 지원하기 때문에 더 빠르다!

벡터는 1차원. 1차원은 방향이 있다? 이 방향은 scala(방향이 없고 크기만 있음) 벡터는 방향과 크기가 둘 다 있는 애. 우리가 배울 1차원 벡터(가로든 세로든 간에)는 방향이 없다고 생각하면 됨.
2차원은 matrix
3차원은 3D Array 패널 데이터라고도 함. 이걸 Tensor라고 부름
Tensorflow는 이 구조를 사용하는 애라는 걸 간접적으로 알 수 있음
이걸 일반화하면 ND array

상식상 이미지는 2차원 데이터
동영샹은 3차원 데이터 <-2차원 데이터를 시간순으로 계속 만든 것
또는 개수까지 하면 4차원으로 만들 수 있음

즉, 핵심은 어떤 현상을 벡터화시키는 것!

이미지는 3차원으로도 표현할 수 있음. RGB! 색깔별로 이미지 하나하나씩 만들어놓고 이걸 겹쳐놓으면 3차원 데이터
4차원으로도 만들 수 있음! 비디오..
어떻게 만들지, 어떻게 최적화할지는 우리의 역할

Numerical Python = Numpy
특히 배열 데이터 사이언티스트들은 이거 배우는 데에 시간이 많이 걸린다고 하면 굳이 이거 안 배움.
이거 배우는 데에 쉽기 때문에 확산속도가 아주 빨랐던 것.
파이썬2가 사실 속도가 더 빨랐음 (바이트 기반! 파이썬3은 유니코드 기반)
파이썬 3.4부터는 속도가 비슷해졌음. 지금은 거의 똑같음.
아무튼 위에 것 때문에 잘 안넘어갔고 넘파이에서 파이썬3지원을 아주 늦게 시작했음 <- 결정적
파이썬3에서 넘파이를 사용 못하니까
넘파이를 만드는 사람이 돈 받아서 회사 키우고 파이썬3 이식해줬음
유일하게 파이썬 공식 연산자인데 넘파이만 쓰는 문법도 있음 이것도 파이썬 재단에서 배려해줬음
그만큼 넘파이의 영향력이 막강

가장 중요한 것 : 우리가 배울 모든 애들은 다 numpy 기반
내가 좀 궁금하다 하면 numpy 코드를 봐야 함
이게 조금 힘들다.



In [1]:
import numpy as np # 기본 내장 함수는 아님

In [2]:
dir(np) # 수학함수가 굉장히 많음

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

dir했을 때와 __dir했을 때의 차이점이 정렬 문제
대문자가 아스키코드상 앞서 있기 때문에 대문자가 먼저 나옴
관례상 파이썬은 상수가 없음.
상수라는 것은 재할당을 못하는 애.
파이썬은 명시적인 상수가 없음
그런데 대문자로 다 이루어져 있으면 상수처럼 쓴다.

보통 데이터는 두 가지 방법으로 생성할 수 있다. 지금부터는 하나 더 알고 있어야 함
1) instant
2) 리터럴 - 파이썬 고유 타입만 지원
3) 디자인 패턴의 문제. 인스턴트화하지 않고 다른 함수의 힘을 빌어서 인스턴트화 - factory method! <-??
넘파이는 factory method가 아주 많음

In [3]:
a = np.array # 대표적인 factory method
# 그런데 파이썬 공식 라이브러리에도 array가 있음
# array라고 하면 일반적으로 homogenius한 데이터 타입을 일컫음.
# homogenius한 애들의 장점? 얘 다음 데이터 타입이 뭐가 올지 체크할 필요가 없음
# -> 속도가 빠르다.
# 파이썬 저 어레이는 넘파이만큼 속도도 안 빠르고 편하지도 않아서 거의 안 씀!! 거의..거의전부다.


C로 저장하는 방식과 Potran으로 저장하는 방식 두 가지를 지원해줌 (넘파이가)
array(object, dtype=None)
object는 array_like array는 기본적으로 homogenius, 그리고 한 개 이상.


In [4]:
a = np.array(1)

In [5]:
a

array(1)

In [6]:
type(a)

numpy.ndarray

In [7]:
a = np.array([1,2]) # list

In [8]:
a

array([1, 2])

In [9]:
a = np.array((1,2))

In [10]:
a # list형태로 바꾼다.

array([1, 2])

얘는 mutable 타입.

mutable이면 골치아픈 게 있음...데이터 막 바꾸면 안된다.
copy 개념 알아야 된다.
swallow copy, deep copy...
mutable에서 나오는 문제점 다 가지고 있음.

일단 데이터 형태가 array
output에 array()나오면 numpy data type

In [11]:
type(a) # 원래 이름은 ndarray..n차원 array

numpy.ndarray

output에 array가 나오면 numpy format이라고 생각하면 됨

나중에 심심찮게 이 array()...가 튀어나옴 -> 싹다 numpy로 만들었다.

In [12]:
a = np.array([[1,2],[3,4]])

In [13]:
a # matrix!

array([[1, 2],
       [3, 4]])

3차원도 만들 수 있음

In [14]:
a = np.array([[[1,2],[3,4]], [[1,2],[3,4]]])

In [15]:
a

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

3차원은 이 중간에 공백이 있음  
판 하나하나마다 공백이 있는 것!

공백 하면 데이터가 겹쳐져 있다는 걸 느낄 수 있어야 함.  
무한 차원까지 늘릴 수 있다.  

In [18]:
type(a)

numpy.ndarray

In [19]:
n = np.ndarray(0)

In [21]:
n # 인스턴스화해서 변수 생성

array([], dtype=float64)

그런데 결과가 약간 미묘하게 다르다.

dtype!

얘는 homogenius...그러면 왜 데이터 타입이 중요할까?

In [24]:
a = np.array([1,2,3])

In [25]:
a

array([1, 2, 3])

In [22]:
a = np.array(['1',2,3])

In [23]:
a

array(['1', '2', '3'], dtype='<U1')

dtype = '<U1'
문자열로 싹 다 바뀜!
호모지니어스하기 때문에 어떤 데이터타입으로 바꿔줌!

In [26]:
n = np.ndarray([0,'1'])

TypeError: 'str' object cannot be interpreted as an integer

얘는 에러!  
인스턴스바꾸는 방법 세가지 (다시)  
1) 클래스 이용해서 인스턴스화  
2) 리터럴 방식 (기호 이용)  
3) 팩토리 메소드 방식 <- 인스턴스화를 좀더 쉽고 편리하게 해주려고 매핑해주는 것  
그냥 인스턴스화했더니 호모지니어스한 데이터가 아니면 에러가 남.  
그런데 팩토리 메소드 쓰면 호모지니어스한 형태로 바꿔줌!  
즉 팩토리 메소드가 편하게 사용할 수 있어서 좋은 것.  
dtype에서 <가 이상!  
numpy는 굉장히 low level  
little endian, big endian 방식 데이터 저장도 지원.  
<~ : little endian  
~> : big endian  

little endian과 big endian  
https://ko.wikipedia.org/wiki/%EC%97%94%EB%94%94%EC%96%B8  
https://dongyeollee.github.io/2018/05/22/Network/Big-Endian-and-Little-Endian/  

빅 엔디언은 소프트웨어의 디버그를 편하게 해 주는 경향이 있다. 사람이 숫자를 읽고 쓰는 방법과 같기 때문에 디버깅 과정에서 메모리의 값을 보기 편한데, 예를 들어 0x59654148은 빅 엔디언으로 59 65 41 48로 표현된다.

반대로 리틀 엔디언은 메모리에 저장된 값의 하위 바이트들만 사용할 때 별도의 계산이 필요 없다는 장점이 있다. 예를 들어, 32비트 숫자인 0x2A는 리틀 엔디언으로 표현하면 2A 00 00 00이 되는데, 이 표현에서 앞의 두 바이트 또는 한 바이트만 떼어 내면 하위 16비트 또는 8비트를 바로 얻을 수 있다. 반면 32비트 빅 엔디언 환경에서는 하위 16비트나 8비트 값을 얻기 위해서는 변수 주소에 2바이트 또는 3바이트를 더해야 한다. 보통 변수의 첫 바이트를 그 변수의 주소로 삼기 때문에 이런 성질은 종종 프로그래밍을 편하게 하는 반면, 리틀 엔디언 환경의 프로그래머가 빅 엔디언 환경에서 종종 실수를 일으키는 한 이유이기도 하다.

또한 가산기가 덧셈을 하는 과정은 LSB로부터 시작하여 자리 올림을 계산해야 하므로, 첫 번째 바이트가 LSB인 리틀 엔디언에서는 가산기 설계가 조금 더 단순해진다. 빅 엔디언에서는 가산기가 덧셈을 할때 마지막 바이트로부터 시작하여 첫 번째 바이트까지 역방향으로 진행해야 한다. 그러나 오늘날의 프로세서는 여러개의 바이트를 동시에 읽어들여 동시에 덧셈을 수행하는 구조를 갖고 있어 두 엔디언 사이에 사실상 차이가 없다.

저장방식에 따라 메모리방식과 속도를 최적화할 수 있다  
넘파이는 자동적으로 C에서 할 수 있는 모든 수치해석을 쉽게 할 수 있다.  
dtype이 또 하나의 중요한 이슈!  
어떤 인스턴스인지 알기 위해서 dir -> 쓸 수 있는 모든 attribute 알 수 있다  
vars -> 인스턴스 변수가 가진 애를 알 수 있다.  

In [27]:
vars(a)

TypeError: vars() argument must have __dict__ attribute

In [29]:
# 에러!
# -> __dict__ 가 정의되어 있지 않음
# 값을 하나만 가짐!

In [28]:
type(a)

numpy.ndarray

In [30]:
a = np.array([[1,2],[3,4]])

In [31]:
a

array([[1, 2],
       [3, 4]])

In [32]:
# 행, 렬 -> 2차원

In [33]:
a.ndim

2

2차원!

In [34]:
len(a)

2

In [36]:
a.shape

(2, 2)

In [39]:
# .ndim이랑 약간 비슷
# 조금 다른 점이 있음
# 좀 더 자세히 알고 싶으면 .shape을 쓰면 됨.
# shape은 굉장히 중요! 행렬 연산할 때 모양을 맞춰줘야 하기 때문에!

In [37]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [38]:
# C방식으로 저장되어 있는지 포트란 방식으로 저장되어 있는지 보여줌!
# C는 옆으로 1,2,3,4 이렇게 연속적으로 저장함.
# 포트란은
# 1 2
# 3 4
# 이렇게 저장
# 즉 1,3,2,4 이렇게
# C는 옆으로, 포트란은 밑으로

In [40]:
a.size
# 원소의 개수

4

In [41]:
a.itemsize
# 각 하나의 애가 몇비트인지

8

얘는 8비트

In [42]:
a.dtype

dtype('int64')

In [43]:
# int64로 저장되어 있음.
# 어떠한 속성을 가지고 있는지 체크하는 메서드들이 굉장히 많음.

In [44]:
b = np.array([[1,2],[3,4]])

In [45]:
x = [1,2,3,4]
y = [2,3,4,5]

In [47]:
x+y # 뒤에 추가됨

[1, 2, 3, 4, 2, 3, 4, 5]

In [49]:
a+b # 행렬계산! 각각 원소끼리 계산해줌

array([[2, 4],
       [6, 8]])

In [50]:
# 훨씬 편하게 벡터연산 할 수 있다
[a+b for a,b in zip(x,y)]
# 저거 안 쓰고 그냥 파이썬에서 벡터연산하려면 이렇게

[3, 5, 7, 9]

In [51]:
a-b

array([[0, 0],
       [0, 0]])

In [52]:
a*b

array([[ 1,  4],
       [ 9, 16]])

이렇게 계산하는 방식을 elementwise방식이라고 함

즉 이 방식은 우리가 수학시간에 배웠던 걸 복잡한 프로그래밍 없이 쉽게 하는 방법.  
그래서 넘파이가 편하다!

In [53]:
a.T # 행과 열을 바꿔줌

array([[1, 3],
       [2, 4]])

선형대수시간에 배웠던 거의 모든 애를 한두개의 명령어를 모두 처리 가능

왜 빠르다? C로 만들어져서.  
그래서 조금 전에 C 데이터타입 지원해준다 까지 봤음.  
또 하나? 벡터화  
for 없이 계산  
또? 호모지니어스

statsmodel : R을 그대로 베낌 R을 베낀 프레임워크  
scikit-imgae : 영상처리할 때 씀  
opencv  
scikit-learn  
pandas  
matplotlib  

특히 pandas 깊게 들어갈 것  

In [54]:
# 특히 Numpy 중에서 사람들이 많이 계산하는 함수들이 있음. 분야별로  
# 특히 과학 분야에서.  
# 아주 많이 사용되는 함수들을 numpy 기반으로 만들어놓은 게 Scipy!
# Scipy는 굳이 많이 사용하는 거 구현할 필요가 없이 여기에서 그냥 가져다 쓰면 됨.
# 눈에 보이는 거? stats, linalg

이제 조금 더 깊게 들어감.  
왜 넘파이가 빠를까? C로 만들어졌고 호모지니어스하고...  
더 자세히 보면 내부구조가...  
파이썬의 리스트는 linked list 형태  
-> 메모리가 일렬로 저장되지 않고 타입이 없기 때문에 타입을 계속 하나하나 체크해야 함.  
넘파이는 데이터를 싹다 일렬로 메모리상에 확보하고 그 위에 데이터를 저장.  
파이썬 리스트 같은 경우에 값 계속 찾는 게 너무 시간이 많이 걸림!  
넘파이는 그럴 필요 없이 인덱스만 체크하면 됨.  
이런 구조이기 때문에 몇번째 무엇을 찾는가가 굉장히 중요!  

header에서 data-type을 체크하고, 몇 번째 애 하면 거기로 바로 jump!  
연산속도가 빠를 수밖에 없는 구조 (파이썬은 엘리먼트마다 일일이 datatype체크)  
strides : 4를 12로 나누면 3 1의 세개짜리가 하나의 형태로 사람들에게 보여주겠다 3행 3열 형태로 내부구조는 무조건 싹다 일렬 사람들한테 보여줄 때만 3x3 형태로 보여주고 관리 메모리 일렬로 하면 다음에 비어있는지 체크할 필요가 없음.  
그런데 왜 12 4로 표시..?   
C에서 포인터 선언하면 메모리 공간 확보.  
얘는 C로 만들었기 때문에 C의 고급 기법을 그대로 적용시킴.  

In [55]:
a.strides

(16, 8)

빠른 이유는 다 했음. 이제 쉽다로 넘어감!

In [56]:
# 우리가 만약 C의 힘을 안 빌렸으면 데이터 타입을 정하는 건 굉장히 어려움.  
# 만약 이미지 처리할 때 RGB의 경우 red, green, blue...256개 -> 2의 8승!
# 그런데 만약 파이썬으로 한다고 하면 2의 8승보다 훨씬 큰 애를 쓸 수밖에 없음.
# 파이썬은 int의 종류가 하나밖에 없으니까.
# 속도도 느리고 메모리 효율성이 떨어짐.
# 한정시키면?
# 파이썬으로 한정시킬 수 있을까? 있음. (인터닝 기법으로)
# 그런데 이거 일일이 만들기 너무 복잠.

첫번째로 쉬운 이유 : 데이터 타입  
numpy가 int를 더 쪼갬!  
long, assigned int, longlong... 얘네도 싹다 지원해줌  
우리는 지원해준다는 것만 알고 여기 수업에서는 무조건 가장 큰 지원범위인 int64, float64만 다룰 것.  
더 작은 범위도 지원해준다. -> 메모리공간 효율적으로 사용할 수 있다.  
데이터 타입 지원해주기만 하면 자기가 알아서 다 처리해준다.  
문자열 파이썬에서 세개 있는데 얘는 리틀앤디언, 빅앤디언까지 지원해준다.  
우리가 수집한 데이터...numpy format으로 바꾸면 아주 효율적으로 처리할 수 있음!  
그다음에 우리가 할 일은 데이터 구조로 바꾸는 것!  
아마 텐서플로우나 케라스나 파이토치 써봤던 사람들은 데이터 처음에 불러오는 함수들 있음. 이렇게 불러오면 데이터 형태가 다 넘파이 형태.  

In [57]:
# from tensorflow.keras.datasets import mnist
# data = mnist.load_data() <- 얘 numpy 형태

쉬운 거? 데이터 타입을 dtype에 얘만 정하면 데이터 타입을 아주 쉽게 변형할 수 있음!  
그런데 정말 많음... u가 붙으면 unsigned 부호가 없음.  
int만 8 + 파이썬 전용(오버플로우 없는 거) 하나더  
이렇게 정말 많음.  
데이터 분석할 때 주니어로 젤 처음에 전처리만 시킴.  
전처리할 때 아주 많이 할 것.  
뒤에 _ 있으면?

## _(underbar)

앞에 _ : 관례상 private처럼 쓴다. 그런데 어떤 때는 관례상이 아니었음. from/import * 썼을 때 _ 붙어 있는 애 import 안 된다.  
앞에 __ : OOP할 때 dir할 때 안나왔음. 이름이 mangling됐음.  
앞에 __ 뒤에 __ : magic method 또는 special method  
그냥 _ : 관례상 필요없는 변수이름일 때
그런데 _ 가 맨 마지막 결과를 나눌 때도 있음 <-?
_(a) : 다국어 처리할 때
이름 뒤에 _ : 관례상 파이썬 키워드하고 똑같을 때 이름 충돌을 피하기 위함
string_ : 파이썬에 string이랑 이름이 비슷하니까 관례상 붙인 것.

In [62]:
a = np.array([[1,2],[3,4]], dtype='u1') # dtype을 단축표현 할 수 있음

In [63]:
a

array([[1, 2],
       [3, 4]], dtype=uint8)

쉽게 다양한 데이터 타입을 하나 찍어서 변환해줄 수 있음!

타입 코드를 이용해서 쉽게 접근할 수 있음! 아니면 어떻게 쓰냐면 np.int8 이런 식으로 길게 써야 함.

그러면 type code가 몇 개 있는지 궁금하니깐..

In [64]:
np.sctypeDict # 이렇게 알아볼 수 있다.

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.int32,
 5: numpy.int32,
 'uint': numpy.uint64,
 'I': numpy.uint32,
 6: numpy.uint32,
 'intp': numpy.int64,
 'p': numpy.int64,
 7: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 8: numpy.uint64,
 'long': numpy.int64,
 'l': numpy.int64,
 'L': numpy.uint64,
 'longlong': numpy.int64,
 'q': numpy.int64,
 9: numpy.int64,
 'ulonglong': numpy.uint64,
 'Q': numpy.uint64,
 10: numpy.uint64,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.float128,
 'g': numpy.float128,
 13: numpy.float128,
 'cfloat': numpy.complex128,
 'F': numpy.complex64,
 14: numpy.complex64,


In [65]:
len(np.sctypeDict) # 158개

158

개수가 다름. 넘파이 버전이 32짜리, 64짜리 이렇게 다르게 설치되었으면 개수가 다름.

In [66]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/eunha/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/eunha/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/eunha/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/eunha/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/eunha/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/eunha/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/eunha/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/eunha/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/eunha/anaconda3/lib']
    de

우리는 complex, bool 안 씀.  
bool은 int랑 똑같으니까.  
우리는 빅데이터 처리할 거니까.  
가장 큰 int64, float64, float128 말고는 사용 안할 것.  
numpy 이용해서 데이터 처리할 거면 저거로 하나하나 체크해야 함.  
## stride 
stride가 일렬로 싹다 저장되어 있는 걸 사람에게 어떻게 표현해주는 것.  
약수로 나눠서 그 개수만큼 보면 얘가 어떤 구조인지 거꾸로 알 수 있음.  
(6,2)인 경우 2로 나누기 때문에 3개가 하나. <-?  
데이터 접근할 때...4는 0에서 4까지 몇번만에 접근할 수 있을까?  
원래는 0,1,2,3,4,5,6  
얘는 무조건 한번만에 접근할 수 있음.  
점프롤 한번만.  
벡터화는 무조건 계산을 한번.  
모든 데이터를 한번만에 접근할 수 있음.  

바이트단위로 생각해보자.  
하나 지나갈 때마나 8byte.  
4바이트면 4, 4, 4.  
3*1에 바이트를 곱하면 12*4가 stride가 됨.  
물론 8byte였을 경우에는 24*8  

세상이 일렬로 되어 있다?  
텐서플로우 처음 배울 때 대부분 mnist 예제 했을 것.  
mnist할 때 행렬 한 열로 바꾸는 flatten시킴.  
해도 상관없음! stride를 알고 있기 때문에.  
"This array is stored in memory as 40 bytes, one after the other (known as a contiguous block of memory). The strides of an array tell us how many bytes we have to skip in memory to move to the next position along a certain axis. For example, we have to skip 4 bytes (1 value) to move to the next column, but 20 bytes (5 values) to get to the same position in the next row. As such, the strides for the array x will be (20, 4)."  
https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.strides.html (참고)  

뉴럴 네트워크 할 때 일차원 배열 넣었음. stride 개념이 있으니까 차원은 내 마음대로 쉽게 변환 가능!  
flatten시키는 이유가 stride 개념이 숨어 있기 때문.  

개념상 아주 편하게 접근할 수 있다.  
차원이 중요치 않을 경우는 다 stride 개념이 숨어 있다.  
stride는 아주 편한 개념!  

그런데 stride가 복잡해질 수 있다.  
numpy는 배열을 저장하는 방식을 두가지 지원..C방식과 포트란 방식.  
C방식일 경우 가로~ 포트란 방식은 세로~  
stride개념이 C로 저장되어있을 때와 potran으로 저장되어있을 때와 다르다.
c : stride(12,4)  
potran : stride(4,12)  
그럼 데이터 찾는 속도가 파이썬은 왔다갔다 해야 되기 때문에 느린데 넘파이는 데이터 찾는 속도가 엄청 빠름!  
빅데이터 되어 있을 때 특정값 찾을 때 굉장히 효율적으로 찾을 수 있다.  
만약 엑셀로 600만개로 되어 있다고 하면 특정값 찾을 때 시간 걸림.  
그런데 넘파이는 우리가 생각할 때 stride 개념 쓰면 사람이 생각하면 두번 메모리 상에서는 한번만 점프하면 되기 때문에 엄청 빠르다.  

## axis
행끼리 계산하는 건 axis=0, 열끼리 계산하는 건 axis=1  
stride되어 있으면 얘네 계산하기 쉬움. 점프점프 하면 되니까!  
즉 행끼리, 열끼리 계산하는 거 아주 속도가 빠르다.  
axis=0은 행, axis=1은 열끼리 배열.  
그럼 axis=0으로 합을 구하라 하면 5/7/9
axis=1로 합을 구하라 하면 6, 15
해서 꼼수로 axis=0이면 shape에서 0번째 지움! 결과 shape[1]개 axis=1이면 shape에서 1번째 지움! 결과 shape[0]개

우리는 지금 내부구조 배우고 있다.

다시 정리.
넘파이는 로우레벨!
깊게 이해하고자 하면 넘파이를 모르면 전체 프레임워크를 이해를 못함. 그러면 암기. 빨리 까먹음!

In [67]:
# range <- 어디부터 어디까지 만들어줌.
a = np.arange(10)

In [68]:
a # range(10)이랑 같은 결과!

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
# reshape은 모양을 바꿀 수 있음.
a.reshape(2,5) # 2행 5열로 바꿔줌

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [70]:
a # mutable인데 a 본체가 안 바뀜

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

mutable 함수의 결과는 세가지  
1) 자기 자신은 바뀌지만 리턴값이 None  
2) 리턴값이 있지만 안바뀌는 경우  
3) 리턴값도 있고 바뀜  
+) copy개념! - swallow copy, deepcopy  
numpy는 조금 더 세분화되어 있음.  
a.reshape하면 카피하는 것!  
그래서 reshape은 재할당해야됨.  

In [71]:
a = a.reshape(2,5)

In [72]:
a.shape

(2, 5)

In [73]:
# 열의 합을 구하려면...?
# 파이썬에서 합 구할 때 sum 있음.
# 파이썬하고 넘파이랑 거의 일대일 매칭됨
a.sum(0)
# a.sum(axis=None, dtype=None, out=None, keepdims=False) axis가 0이면 결과 다섯개 나올 것!

array([ 5,  7,  9, 11, 13])

In [74]:
a.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [75]:
a.sum(axis=1)

array([10, 35])

In [76]:
a.sum() # 안 집어넣으면 전체 다 구해줌!

45

axis를 집어넣으면 내가 필요한 애만 해서 계산할 수 있음.

In [77]:
a.mean()

4.5

In [78]:
a.mean(axis=0)

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [79]:
a.mean(axis=1)

array([2., 7.])

점수 같은 거 계산할 때 응용하기 좋음.

한방에 편하게 구해짐! axis 안에 숨어 있는 개념은 stride 개념!

In [82]:
%time sum(x for x in range(1000000000))

CPU times: user 41.3 s, sys: 8.33 ms, total: 41.3 s
Wall time: 41.3 s


499999999500000000

In [83]:
%time np.sum(np.arange(1000000000))

CPU times: user 2.35 s, sys: 1.8 s, total: 4.15 s
Wall time: 4.17 s


499999999500000000

16배 빠름!

미리 구현하고 최적화하지만 보통  
그런데 넘파이로는 처음부터 최적화되어 있기 때문에 넘파이를 이용해서 코딩하면 자동적으로 최적화됨.

그래서 넘파이 먼저 배움.

matlab은 데이터의 기본구조가 matrix  
R은 데이터의 기본구조가 벡터  
넘파이는 매트릭스를 지원해줌 (그런데 안 쓸 것)  
왜 안 쓰는가? 매트릭스는 고정되어 있음 딱 2차원.  
그런데 matlab쓰는 사람들은 습관이 되니까 항상 matrix로 생성  

그래서 공식 홈페이지에 matlab 유저를 위한 numpy 문서가 나와 있음.  
15년 전만 해도 이 분야에서 matlab만 사용했음.  
matlab이 예전엔 공짜가 아니었음.  
비싼데 일년 업그레이드 정책을 해서 매 일년마다 돈 써야 됐음.  
그래서 대응이 막 나와서 넘파이도 생긴 거고 R도  
matlab의 단점이 매트릭스 기반이다 보니 유연하지 못함  
벡터 기반이면 좀더 유연할 수 있음.  
여기서 매트릭스를 안 하는 이유가 넘파이가 R하고 같이 배우기가 좋음 (벡터 기반으로 하면)  
매트릭스도 있다! 이 정도.  

이제부터 조금 재밌는거...  

np.array로 만들면 좀 불편할 수 있음. 다 하나씩 집어넣어야 함.

In [85]:
# zeros(shape, dtype=float, order='C') shape 넣어야 함!
a = np.zeros((3,4)) # 배열 0으로 만들기

In [86]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [87]:
a = np.ones((3,4)) # 배열 1로 만들기

In [88]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [89]:
# 똑같은 걸로 만들기 3으로? threes는 없고
# np.full(shape, fill_value, dtype=None, order='C')
# numpy는 기본적으로 싹다 C 기반
c = np.full((3,4), 6)

In [90]:
c

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [91]:
d = np.full((3,4), 0)

In [92]:
d

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [93]:
# np.zeros_like(a, dtype=None, order='K', subok=True)
a = np.zeros((3,4))
d = np.ones_like(a)

In [94]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [96]:
d # a하고 shape은 똑같은데 like 1로 다 만들어줌!

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

행렬 연산할 때 shape가 중요! 똑같아야 하기 때문에 like아주 자주 사용!

단위행렬

In [97]:
# np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
# 정방행렬만 단위행렬이기 때문에 shape이 아니고 N
b = np.eye(3)

In [100]:
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
# np.identity(n, dtype=None)
c = np.identity(3)

In [99]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

eye는 조금더 많은 옵션이 있는 거고 identity는 옵션 없이 좀더 빠르게 만들 수 있음.  
두개 다 단위행렬 만드는 것.

In [102]:
# 선형대수학에서 배우는 행렬
# 직교행렬
# np.tri(N, M=None, k=0, dtype=<class 'float'>)
b = np.tri(3)

In [103]:
b

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

이름있는 행렬들 다 만들 수 있음  
상삼각행렬, 하삼각행렬

In [104]:
b = np.tril((3,3))

In [105]:
b

array([[3, 0],
       [3, 3]])

In [106]:
b = np.triu((3,3))

In [107]:
b

array([[3, 3],
       [0, 3]])

In [108]:
# 전치행렬
b.T

array([[3, 0],
       [3, 3]])

In [109]:
# 전치행렬
np.transpose(b)

array([[3, 0],
       [3, 3]])

두번째 arrange하고 비슷하지만 구간별로 잘라서 만들 수 있는 게 있음.

In [110]:
# np.linspace(
#     start,
#     stop,
#     num=50,
#     endpoint=True,
#     retstep=False,
#     dtype=None,
#     axis=0,
# )
d = np.linspace(0,100)

In [111]:
d

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [112]:
d = np.linspace(0,99)

In [113]:
d

array([ 0.        ,  2.02040816,  4.04081633,  6.06122449,  8.08163265,
       10.10204082, 12.12244898, 14.14285714, 16.16326531, 18.18367347,
       20.20408163, 22.2244898 , 24.24489796, 26.26530612, 28.28571429,
       30.30612245, 32.32653061, 34.34693878, 36.36734694, 38.3877551 ,
       40.40816327, 42.42857143, 44.44897959, 46.46938776, 48.48979592,
       50.51020408, 52.53061224, 54.55102041, 56.57142857, 58.59183673,
       60.6122449 , 62.63265306, 64.65306122, 66.67346939, 68.69387755,
       70.71428571, 72.73469388, 74.75510204, 76.7755102 , 78.79591837,
       80.81632653, 82.83673469, 84.85714286, 86.87755102, 88.89795918,
       90.91836735, 92.93877551, 94.95918367, 96.97959184, 99.        ])

In [114]:
e = np.logspace(1,100)

In [115]:
e # log값으로 잘라줌

array([1.00000000e+001, 1.04811313e+003, 1.09854114e+005, 1.15139540e+007,
       1.20679264e+009, 1.26485522e+011, 1.32571137e+013, 1.38949549e+015,
       1.45634848e+017, 1.52641797e+019, 1.59985872e+021, 1.67683294e+023,
       1.75751062e+025, 1.84206997e+027, 1.93069773e+029, 2.02358965e+031,
       2.12095089e+033, 2.22299648e+035, 2.32995181e+037, 2.44205309e+039,
       2.55954792e+041, 2.68269580e+043, 2.81176870e+045, 2.94705170e+047,
       3.08884360e+049, 3.23745754e+051, 3.39322177e+053, 3.55648031e+055,
       3.72759372e+057, 3.90693994e+059, 4.09491506e+061, 4.29193426e+063,
       4.49843267e+065, 4.71486636e+067, 4.94171336e+069, 5.17947468e+071,
       5.42867544e+073, 5.68986603e+075, 5.96362332e+077, 6.25055193e+079,
       6.55128557e+081, 6.86648845e+083, 7.19685673e+085, 7.54312006e+087,
       7.90604321e+089, 8.28642773e+091, 8.68511374e+093, 9.10298178e+095,
       9.54095476e+097, 1.00000000e+100])

In [116]:
e = np.empty((4,2))

In [117]:
e

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

C에서 선언만 하면 쓰레기값 들어간 것과 비슷. 비어 있는 게 아니고 초기화되지 않은 값이 들어감.

쉽게 만드는 거 다양하게 지원해준다!

만들었으면 이제 특정 애 뽑아냄!

In [119]:
a = np.arange(10).reshape(2,5)

In [120]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

두가지 뽑아내는 개념 : indexing, slicing, indexerror나왔던 거랑 비슷한 에러 나왔던 거 keyerror index하고 key  
index하고 slice가 지원하는 타입은 시퀀스 타입. 시퀀스 타입은 순서가 중요.  
넘파이는 순서가 중요.  
-> 인덱싱 됨.

In [121]:
# 그런데 인덱싱 방법이 조금 확장되어 있다.
# python에서는 8을 뽑아내기 위해서
a[1][3]

8

기본적인 파이썬 방식

numpy에서는 조금더 고급적인 애를 지원해준다.

In [122]:
a[1,3]

8

얘는 파이썬에서 지원해주는 애 아님! 아주 빠르게 내가 원하는 거 뽑아낼 수 있다.  

In [123]:
a[:,3]

array([3, 8])

모든 행에서 네번째 거 뽑아내줌!

특정 열 뽑아내거나 특정 행 뽑아내는 거 편하게 할 수 있다.

In [124]:
a = np.arange(27).reshape(3,3,3)

In [125]:
a # 3차원

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [128]:
a[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [129]:
a[1,:] # 두개밖에 없어도 지가 알아서 전체 다 가지고와줌

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [130]:
a[1,...] # ...은 전부다라는 애를 지원해줌

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

굉장히 다양한 방식으로 인덱싱, 슬라이싱 해준다.

사실 파이썬도 ...있음!

In [133]:
a[:,:,1] # 모든 판의 모든 행에서 첫번째 열의 값을 다 뽑아옴

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [134]:
a[...,1]

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [135]:
a[:,1] # 앞에는 줄여쓰는 거 안됨

array([[ 3,  4,  5],
       [12, 13, 14],
       [21, 22, 23]])

In [136]:
a[:,1,:]

array([[ 3,  4,  5],
       [12, 13, 14],
       [21, 22, 23]])

In [138]:
a[:,2::2,::2] # ::은 ~간격으로

array([[[ 6,  8]],

       [[15, 17]],

       [[24, 26]]])

In [139]:
a[a>3] # condition 추가 가능

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26])

In [140]:
a[a>3 & a<8] # 그냥은 오류

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [141]:
a[(a>3) & (a<8)] # 괄호치면 오류 안남

array([4, 5, 6, 7])

In [142]:
a[(a>3) | (a<8)] # or

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [155]:
a = np.arange(10)

In [156]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
a[[True,False,True,True,True,True,True,True,True,True]] #false인 애는 안 뽑히고 true만 뽑힘

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [158]:
a>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

fancyindexing

In [152]:
a=np.arange(15).reshape(5,3)

In [153]:
a[[1,2]] # 1행, 2행을 뽑아줌

array([[3, 4, 5],
       [6, 7, 8]])

In [154]:
a[[-1,-2]]

array([[12, 13, 14],
       [ 9, 10, 11]])

내일 오후부터는 판다스 배움.  
정형 데이터에서 특정 데이터를 뽑아오기가 너무 쉬움!  
1) 조건ok  
2) 마스킹 기법ok  
3) fancyindexing  
4) ,  
5) ...  
numpy에서 지원하는 새로운 인덱싱 기법  
numpy기반 pandas는 이거보다 또 추가된 인덱싱 기법 지원해줌  

In [159]:
a = np.arange(10).reshape(5,2)

In [160]:
a[[1,3]]

array([[2, 3],
       [6, 7]])

In [161]:
a[[1,2]][:,1]

array([3, 5])

fancyindexing은 pandas에서 또 나옴

다양한 방법으로 인덱싱 슬라이싱이 가능하다!

In [162]:
a = np.arange(36).reshape(6,6)

In [163]:
a[(0,1,2,3,4),(1,2,3,4,5)] #(0,1),(1,2)...이렇게 뽑아줌

array([ 1,  8, 15, 22, 29])

In [164]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [166]:
mask = np.ndarray([1,0,1,0,0,1],dtype=bool)

In [167]:
a = np.arange(25).reshape(5,5)

In [170]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [168]:
a[0]

array([0, 1, 2, 3, 4])

In [169]:
a[1, 3:5]

array([8, 9])

In [171]:
a[:,4]

array([ 4,  9, 14, 19, 24])

In [172]:
a[-2:,-2:]

array([[18, 19],
       [23, 24]])

In [173]:
a[2::2, ::2]

array([[10, 12, 14],
       [20, 22, 24]])

In [174]:
a[0,1]

1

In [175]:
a[[0,1]]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [176]:
a[[1,2,4],[2,3,4]]

array([ 7, 13, 24])

In [177]:
a[3:,[0,1,3]]

array([[15, 16, 18],
       [20, 21, 23]])

In [178]:
mask = np.array([0,1,0,0,1], dtype=np.bool)

In [179]:
a[mask,1]

array([ 6, 21])

*__숨어 있는 개념이 stride__*  
만약 이거 안하면 다 for 돌려서 뽑아내야 함  

지금까지 인덱싱과 슬라이싱~~  
넘파이가 시퀀스 타입.  
시퀀스 타입은 또 for 다음에 쓸 수 있다.  
그런데 for 다음에 쓰면 쓸 수는 있지만 벡터라이즈한 기법이 아니기 때문에 numpy를 for 쓰면 안됨!  

In [181]:
# np.nditer(self, /, *args, **kwargs)
b = np.nditer(a)

In [192]:
next(b)

array(9)

python에 있는 것과 거의 비슷한 메서드가 꼭 있음!  
주의할 점은 for 쓰면 벡터라이즈 개념에 어긋난다! (가능은 함)  

In [194]:
def add_(a,b):
    return a+b

만약 이런 함수는 벡터라이즈 함수일까 아닐까?

In [196]:
x=np.arange(5)
y=np.arange(5)

In [197]:
add_(x,y)

array([0, 2, 4, 6, 8])

+니까 이런 게 됨! +함수가 넘파이에 있으니까.

이제 함수도 잘 고려해서 만들어야 함!

## broadcasting

In [198]:
x

array([0, 1, 2, 3, 4])

In [199]:
x*3

array([ 0,  3,  6,  9, 12])

In [202]:
1+[1,2,3]

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [201]:
x+3 # 얘는 됨

array([3, 4, 5, 6, 7])

이런 기법을 브로드캐스팅 기법 <- 편한 이유 중 하나!  
간단한 크기는 자기가 알아서 맞춰준다.  

In [203]:
[1,2] + np.arange(10) # 복잡하면 자동적으로 크기를 안맞춰줌

ValueError: operands could not be broadcast together with shapes (2,) (10,) 

In [205]:
np.ndarray([1,2]) + np.arange(10) # ValueError: operands could not be broadcast together with shapes (1,2) (10,) 

ValueError: operands could not be broadcast together with shapes (1,2) (10,) 

모양이 너무 다르면 자동화할 수 없기 때문에 브로드캐스팅 에러가 튀어나온다.  

쉬운 이유는 아까 인덱싱과 슬라이싱 (첫번째)  
두번째는 브로드캐스팅

## ufunc (쉬운 이유 세번째)

ufunction  
u : universial, 보편적인  
스칼라에서도 지원되고 벡터에도 지원되고 범용적으로 지원되는 함수가  
ufunc 또는 universial function  

In [206]:
abs(-1) # 파이썬 기본 내장 절댓값 함수

1

In [207]:
abs([-1,1,2]) # error

TypeError: bad operand type for abs(): 'list'

In [208]:
np.abs([-1,1,2]) # no error 이게 더 좋음 값 한개짜리에도 씀

array([1, 1, 2])

속도 빠르고 쉬움! 에러 안 남

그래서 다 넘파이로 만들었음.  
엄청나게 많은 함수가 있다.  
숫자 관련되어서...  

In [210]:
np.ceil([2.9,1,2,3,0,3]) # 올림 함수

array([3., 1., 2., 3., 0., 3.])

In [211]:
np.ceil(2.9) # Type: ufunc -> 여러개 동시 계산도 되고 하나 계산도 된다!

3.0

파이썬에 있는 함수는 대부분 넘파이에 있다고 생각하면 됨!

In [212]:
np.info(np.ceil) # numpy 자체에서 설명 보는 방법! (shift+tap으로 안나오는 것들)

ceil(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the ceiling of the input, element-wise.

The ceil of the scalar `x` is the smallest integer `i`, such that
`i >= x`.  It is often denoted as :math:`\lceil x \rceil`.

Parameters
----------
x : array_like
    Input data.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
y : ndarray or scalar
    The ceilin

ufunc이라고 나온 애들은 설명이 부실해서 info해서 볼 것 얘네는 대부분 빌트인 함수와 일대일 매칭됨.  
scipy함수는 훨씬 복잡한 애들 훨씬 고급적인 애들  
numpy 자체에 ufunc은 좀더 간단한 애들.  
factorial 뭐로 만들까?  
factorial은 점화식으로 표현할 수 있다. -> 재귀함수로 만들 수 있다.  
점화식은 파이썬에서 별로 안 좋다!!  
그 해결책으로 scipy에서...

In [213]:
from scipy.special import factorial

In [214]:
factorial(10)

array(3628800.)

In [215]:
factorial(3)

array(6.)

In [217]:
factorial([3,4,5]) # scipy에서 웬만한 거 다 만들어져 있음! 그걸 어떻게 빨리 찾느냐가 핵심

array([  6.,  24., 120.])

In [219]:
np.info(factorial) # scipy에서 가져왔는데 numpy에서 보여짐 <- scipy도 numpy로 만들었기 때문에

 factorial(n, exact=False)

The factorial of a number or array of numbers.

The factorial of non-negative integer `n` is the product of all
positive integers less than or equal to `n`::

    n! = n * (n - 1) * (n - 2) * ... * 1

Parameters
----------
n : int or array_like of ints
    Input values.  If ``n < 0``, the return value is 0.
exact : bool, optional
    If True, calculate the answer exactly using long integer arithmetic.
    If False, result is approximated in floating point rapidly using the
    `gamma` function.
    Default is False.

Returns
-------
nf : float or int or ndarray
    Factorial of `n`, as integer or float depending on `exact`.

Notes
-----
For arrays with ``exact=True``, the factorial is computed only once, for
the largest input, with each other result computed in the process.
The output dtype is increased to ``int64`` or ``object`` if necessary.

With ``exact=False`` the factorial is approximated using the gamma
function:

.. math:: n! = \Gamma(n+1)

Examples


그래서 numpy가 아주 많이 숨어 있음.

In [220]:
# np.iinfo(int_type)
# integer type에 대한 information을 알려줌!
np.iinfo()

ValueError: Invalid integer data type 'O'.

In [221]:
# where(condition, [x, y])
np.where() # 조건을 쓸 때!

TypeError: where() takes at least 1 argument (0 given)

In [226]:
b = np.arange(5, 10)

In [231]:
b

array([5, 6, 7, 8, 9])

In [227]:
np.where(b>5) # 그냥 쓰면 조건을 만족하는 인덱스를 알려준다

(array([1, 2, 3, 4]),)

In [228]:
np.where(b>5, 0, 1) # 5보다 크면 0으로 바꾸고 아니면 1로 바꿔라

array([1, 0, 0, 0, 0])

In [229]:
b[np.where(b>5)] # b에서 조건을 만족하는 인덱스에 해당하는 값들

array([6, 7, 8, 9])

np.where는 index 뽑는 거 말고 변화시키는 기능이 있다!

In [232]:
np.max(b) # 가장 큰 수

9

In [234]:
np.argmax(b) # 가장 큰 수의 인덱스

4

In [236]:
np.argmin(b) # 가장 작은 수의 인덱스

0

3총사  
where, argmax, argmin

여기서 약간 복잡한 게 있음...

In [238]:
b.argmin() # 클래스할 때 함수로 사용하는 방법도 있고 메서드로 사용하는 방법도 있다.
# 함수로 사용할 땐 np.argmin(b), 메서드로 사용할 땐 b.argmin()
# 두가지 방법 다 지원하는 게 대부분인데 간혹 지원 안하는 게 있음
# 파이썬은 펑션과 메서드 간 경계가 아주 약했음

0

쉬운 건 여기까지

가장 중요한 두 개 뽑으라면 shape, dtype  
array가 나오면 Numpy type이다  
a.dtype.name에서 .name생략해도 똑같은 결과 나옴

In [239]:
from numpy import pi

In [240]:
from math import pi as mpi

In [241]:
pi

3.141592653589793

In [242]:
mpi

3.141592653589793

In [243]:
pi == mpi

True

numpi라고 해서 파이썬의 수학에 있는 패키지와 똑같음

간혹 이런 애들도 있음.  
굳이 새로 만들 필요 없는데 왜 만들어졌냐면 얘를 import할 때  
math를 한 번 더 import하면 메모리에 다 올라가니까 효율성이 떨어져서

실수 많이 할 때 얘네 두개를 다른 걸로 보는 경우가 있는데 아님!

In [244]:
pi is mpi

False

다른 memory에 올라가 있기 때문에.

그런데 pi는 memory가 중요한 게 아니고 값만 중요함

numpy.random.rand <-이건 판다스 끝나고 나서 할 것  
굉장히 중요한 애  
우리가 만든 알고리즘에 랜덤한 애에서도 돌아가야 함.  
CS에서 완벽한 random은 없다.  
그래서 랜덤 시드 넣어서 만들 것임.  
fromfunction, fromfile은 파이썬에 있는 것하고 거의 똑같음. <-얘도 판다스 할 때 할 것임  

In [245]:
type(...)

ellipsis

... 자체가 파이썬에 정의되어 있음

In [246]:
dir(...)

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

... 알려줬지만 쓰지 말것!  
실수 제일 많이 하는 것 중 한가지

In [247]:
vars(...) # __dict__ 없음

TypeError: vars() argument must have __dict__ attribute

아주 길 때 내가 몇 개 볼지 option을 줄 수 있음  
np.set_printoptions(threshold=np.nan)  
np.nan?

In [248]:
np.nan # nan; not a number

nan

In [249]:
float('nan')

nan

In [250]:
np.nan == float('nan') # 이런 애들은 외울 수밖에 없음

False

In [253]:
t = float('nan')

In [254]:
np.set_printoptions(threshold=t)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

In [255]:
np.set_printoptions(threshold=np.nan)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

In [256]:
np.newaxis # 다음 시간에 할 것

In [258]:
np.info('newaxis')

     *** Found in numpy ***
 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x103f67400>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.

In [259]:
np.newaxis is None

True

@ : numpy 때문에 만든 연산자 (행렬곱)  
이건 numpy만 사용할 수 있음.

*는 elementwise  
즉 순서대로 곱해줌  
@는 행렬곱

A.dot(B) 내적곱인데 실제로 여기서는 행렬곱으로 사용.  
행렬곱은 두가지 방식

In [260]:
a = np.arange(10).reshape(2,5)

In [261]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

얘가 swallow copy냐 deepcopy냐 할 때

In [262]:
b = a

In [263]:
a[0][0] = 100

In [264]:
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [265]:
b # 아직 카피 안했음

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [266]:
c = b.copy() # 파이썬에서는 copy()하면 swallow copy

In [268]:
b[0][0] = -100

In [269]:
b

array([[-100,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [270]:
c # deepcopy 파이썬하고 반대

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

왜? numpy는 기본적으로 다 중첩시킴.  
deepcopy하면 길기 때문에 copy  

In [271]:
d = b.view() # swallowcopy

In [272]:
b[0][0] = 2000

In [273]:
b

array([[2000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [274]:
d

array([[2000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

약간 혼동됨

왜 카피? 원본을 보관하기 위해서

과제는 numpy tutorial의 link를 크롤링해서 정리...  
div main 안에 있는 링크만 가져와서  
자동으로 표에 집어넣어서 설명 파싱...?  
이런 거 있다 한번씩 보기

wikilink라는 것도 있음. mindmap 이용해서 자기 메뉴얼 생성  

# 내일은 numpy의 안했던 부분, scipy, matplatlib, pandas